-- Lecture unique du RUN : requêtes AVANT (qualification + ingestion) et APRÈS (règle d'adoption simulée), par source et
-- au total, sur le RUN quotidien réel du 01/10/2026 (`ingest-all`). LECTURE SEULE. Rejouable :
--   python3 apps/aggregator/scripts/ops/db.py readonly \
--     sh -c 'psql "$DATABASE_URL" -XA -F"|" -f audits/2026-10-02/lecture-unique/requetes.sql' > audits/2026-10-02/lecture-unique/requetes.out
-- Règle simulée (celle du code, `capture/adoption.ts`) : la capture de qualification du même RUN est adoptée si elle est
-- EXTRACTED, VALIDATED par sa propre validation, non tronquée (énumération non INCOMPLETE, pas ENUMERATION_INCOMPLETE),
-- lue sans transport non pris en charge, et âgée d'au plus 60 min au début de l'ingestion. Sinon le site est relu.
\pset footer off
\set run_jour '2026-10-01'
-- 1. Total, avant et après.
with lots as (select b.id, b."sourceKey", b."accessDecisionId" is not null sous_decision, b."startedAt", b."attemptOrdinal", (select count(*) from "RawCapture" r where r."batchId" = b.id) requetes, o.status, o."transportCoverage" transport, v.verdict, v.report->>'enumerationClaim' enumeration, (v.report->'reasons') ? 'ENUMERATION_INCOMPLETE' tronquee from "CaptureBatch" b join "PipelineRun" p on p.id = b."runId" left join "CaptureOutcome" o on o."batchId" = b.id left join lateral (select verdict, report from "SourceValidation" sv where sv."captureBatchId" = b.id order by sequence limit 1) v on true where b.purpose = 'JOBS' and p.command = 'ingest-all' and p."startedAt" >= :'run_jour' and p."startedAt" < (date :'run_jour' + 1)), par_source as (select s."sourceKey", q.id qualif, q.requetes req_qualif, q.status st_qualif, q.verdict verdict_qualif, q.enumeration, q.tronquee, q.transport, i.id ingest, i.requetes req_ingest, i.status st_ingest, round(extract(epoch from (i."startedAt" - q."startedAt")) / 60.0, 1) age_min, coalesce(q.id is not null and i.id is not null and q.status = 'EXTRACTED' and q.verdict = 'VALIDATED' and coalesce(q.enumeration, '') <> 'INCOMPLETE' and not coalesce(q.tronquee, false) and coalesce(q.transport, '') <> 'UNSUPPORTED_TRANSPORT' and i."startedAt" - q."startedAt" <= interval '60 minutes', false) adoptable from (select distinct "sourceKey" from lots) s left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and not l.sous_decision order by "attemptOrdinal" desc limit 1) q on true left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and l.sous_decision order by "attemptOrdinal" desc limit 1) i on true)
select count(*) sources, count(qualif) requalifiees, count(*) filter (where adoptable) adoptees,
       sum(coalesce(req_qualif, 0) + coalesce(req_ingest, 0)) requetes_avant,
       sum(case when adoptable then req_qualif else coalesce(req_qualif, 0) + coalesce(req_ingest, 0) end) requetes_apres,
       sum(req_ingest) filter (where adoptable) requetes_evitees
  from par_source;
-- 2. Pourquoi une qualification ne serait pas adoptée.
with lots as (select b.id, b."sourceKey", b."accessDecisionId" is not null sous_decision, b."startedAt", b."attemptOrdinal", (select count(*) from "RawCapture" r where r."batchId" = b.id) requetes, o.status, o."transportCoverage" transport, v.verdict, v.report->>'enumerationClaim' enumeration, (v.report->'reasons') ? 'ENUMERATION_INCOMPLETE' tronquee from "CaptureBatch" b join "PipelineRun" p on p.id = b."runId" left join "CaptureOutcome" o on o."batchId" = b.id left join lateral (select verdict, report from "SourceValidation" sv where sv."captureBatchId" = b.id order by sequence limit 1) v on true where b.purpose = 'JOBS' and p.command = 'ingest-all' and p."startedAt" >= :'run_jour' and p."startedAt" < (date :'run_jour' + 1)), par_source as (select s."sourceKey", q.id qualif, q.requetes req_qualif, q.status st_qualif, q.verdict verdict_qualif, q.enumeration, q.tronquee, q.transport, i.id ingest, i.requetes req_ingest, i.status st_ingest, round(extract(epoch from (i."startedAt" - q."startedAt")) / 60.0, 1) age_min, coalesce(q.id is not null and i.id is not null and q.status = 'EXTRACTED' and q.verdict = 'VALIDATED' and coalesce(q.enumeration, '') <> 'INCOMPLETE' and not coalesce(q.tronquee, false) and coalesce(q.transport, '') <> 'UNSUPPORTED_TRANSPORT' and i."startedAt" - q."startedAt" <= interval '60 minutes', false) adoptable from (select distinct "sourceKey" from lots) s left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and not l.sous_decision order by "attemptOrdinal" desc limit 1) q on true left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and l.sous_decision order by "attemptOrdinal" desc limit 1) i on true)
select case when qualif is null then 'aucune qualification (validation encore fraîche)'
            when st_qualif <> 'EXTRACTED' then 'qualification ' || st_qualif
            when verdict_qualif is distinct from 'VALIDATED' then 'qualification ' || coalesce(verdict_qualif, 'non validée')
            when enumeration = 'INCOMPLETE' or tronquee then 'énumération incomplète ou tronquée'
            when transport = 'UNSUPPORTED_TRANSPORT' then 'transport non pris en charge'
            when ingest is null then 'aucune ingestion (source arrêtée avant)'
            when age_min > 60 then 'plus de 60 min'
            else 'adoptée' end motif, count(*) sources, sum(coalesce(req_qualif, 0) + coalesce(req_ingest, 0)) requetes
  from par_source group by 1 order by 2 desc;
-- 3. Âge de la capture adoptée au début de l'ingestion (minutes) : distribution.
with lots as (select b.id, b."sourceKey", b."accessDecisionId" is not null sous_decision, b."startedAt", b."attemptOrdinal", (select count(*) from "RawCapture" r where r."batchId" = b.id) requetes, o.status, o."transportCoverage" transport, v.verdict, v.report->>'enumerationClaim' enumeration, (v.report->'reasons') ? 'ENUMERATION_INCOMPLETE' tronquee from "CaptureBatch" b join "PipelineRun" p on p.id = b."runId" left join "CaptureOutcome" o on o."batchId" = b.id left join lateral (select verdict, report from "SourceValidation" sv where sv."captureBatchId" = b.id order by sequence limit 1) v on true where b.purpose = 'JOBS' and p.command = 'ingest-all' and p."startedAt" >= :'run_jour' and p."startedAt" < (date :'run_jour' + 1)), par_source as (select s."sourceKey", q.id qualif, q.requetes req_qualif, q.status st_qualif, q.verdict verdict_qualif, q.enumeration, q.tronquee, q.transport, i.id ingest, i.requetes req_ingest, i.status st_ingest, round(extract(epoch from (i."startedAt" - q."startedAt")) / 60.0, 1) age_min, coalesce(q.id is not null and i.id is not null and q.status = 'EXTRACTED' and q.verdict = 'VALIDATED' and coalesce(q.enumeration, '') <> 'INCOMPLETE' and not coalesce(q.tronquee, false) and coalesce(q.transport, '') <> 'UNSUPPORTED_TRANSPORT' and i."startedAt" - q."startedAt" <= interval '60 minutes', false) adoptable from (select distinct "sourceKey" from lots) s left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and not l.sous_decision order by "attemptOrdinal" desc limit 1) q on true left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and l.sous_decision order by "attemptOrdinal" desc limit 1) i on true)
select count(*) n, min(age_min), percentile_cont(0.5) within group (order by age_min) mediane,
       percentile_cont(0.95) within group (order by age_min) p95, max(age_min)
  from par_source where qualif is not null and ingest is not null;
-- 4. Par source : avant, après (trié par économie).
with lots as (select b.id, b."sourceKey", b."accessDecisionId" is not null sous_decision, b."startedAt", b."attemptOrdinal", (select count(*) from "RawCapture" r where r."batchId" = b.id) requetes, o.status, o."transportCoverage" transport, v.verdict, v.report->>'enumerationClaim' enumeration, (v.report->'reasons') ? 'ENUMERATION_INCOMPLETE' tronquee from "CaptureBatch" b join "PipelineRun" p on p.id = b."runId" left join "CaptureOutcome" o on o."batchId" = b.id left join lateral (select verdict, report from "SourceValidation" sv where sv."captureBatchId" = b.id order by sequence limit 1) v on true where b.purpose = 'JOBS' and p.command = 'ingest-all' and p."startedAt" >= :'run_jour' and p."startedAt" < (date :'run_jour' + 1)), par_source as (select s."sourceKey", q.id qualif, q.requetes req_qualif, q.status st_qualif, q.verdict verdict_qualif, q.enumeration, q.tronquee, q.transport, i.id ingest, i.requetes req_ingest, i.status st_ingest, round(extract(epoch from (i."startedAt" - q."startedAt")) / 60.0, 1) age_min, coalesce(q.id is not null and i.id is not null and q.status = 'EXTRACTED' and q.verdict = 'VALIDATED' and coalesce(q.enumeration, '') <> 'INCOMPLETE' and not coalesce(q.tronquee, false) and coalesce(q.transport, '') <> 'UNSUPPORTED_TRANSPORT' and i."startedAt" - q."startedAt" <= interval '60 minutes', false) adoptable from (select distinct "sourceKey" from lots) s left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and not l.sous_decision order by "attemptOrdinal" desc limit 1) q on true left join lateral (select * from lots l where l."sourceKey" = s."sourceKey" and l.sous_decision order by "attemptOrdinal" desc limit 1) i on true)
select "sourceKey", coalesce(req_qualif, 0) qualif, coalesce(req_ingest, 0) ingest, coalesce(req_qualif, 0) + coalesce(req_ingest, 0) avant,
       case when adoptable then req_qualif else coalesce(req_qualif, 0) + coalesce(req_ingest, 0) end apres, adoptable, age_min, st_qualif, verdict_qualif, st_ingest
  from par_source order by coalesce(req_ingest, 0) * adoptable::int desc, "sourceKey";
-- 5. Les deux sources Avature, 01/10 et 02/10 (RUN et collectes ciblées de la release r5) : chaque collecte, son rôle,
--    ses requêtes, son issue, et sa validation. Après la règle : la qualification adoptée, l'ingestion n'a pas lieu.
select b."sourceKey", left(b.id, 8) lot, coalesce(p.command, '-') commande, to_char(b."startedAt", 'MM-DD HH24:MI:SS') debut,
       case when b."accessDecisionId" is null then 'qualification' else 'ingestion' end role,
       (select count(*) from "RawCapture" r where r."batchId" = b.id) requetes, o.status, o."extractedCount" extraites,
       (select sv.verdict || '/' || coalesce(sv.report->>'enumerationClaim', '?') from "SourceValidation" sv where sv."captureBatchId" = b.id order by sequence limit 1) validation
  from "CaptureBatch" b left join "PipelineRun" p on p.id = b."runId" left join "CaptureOutcome" o on o."batchId" = b.id
 where b."sourceKey" in ('ralph-lauren-avature', 'l-oreal-professionnel') and b.purpose = 'JOBS' and b."startedAt" >= '2026-10-01'
 order by b."sourceKey", b."attemptOrdinal";
