import { normalizeContract } from './contract.js';
import { extractSkills } from './skills.js';

/**
 * Taxonomie Catwalks Intelligence (D38) : la famille de métier, la séniorité,
 * le caractère retail et le caractère IA d'une offre, classés à l'écriture
 * depuis ce que la source publie — le titre d'abord, le département ensuite.
 *
 * Une taxonomie du SECTEUR, pas « Sales / Marketing » : un Client Advisor, un
 * Store Manager, un Visual Merchandiser, un maroquinier et un horloger sont
 * des métiers distincts, et c'est cette finesse qui rend l'observatoire utile
 * à un DRH de Maison. Non classé = null, jamais deviné : la couverture est
 * affichée à côté de chaque chiffre.
 *
 * `TAXONOMY_VERSION` monte à chaque changement de règles : une offre dont la
 * version est en retard est re-classée à sa prochaine ré-attestation, et le
 * backfill `classify-jobs` rejoue toute la base.
 */
export const TAXONOMY_VERSION = 1;

export type JobFamily = 'retail' | 'craft' | 'corporate';

export type JobFunction =
  | 'retail-client-advisor'
  | 'beauty-advisor'
  | 'retail-store-management'
  | 'retail-area-management'
  | 'retail-operations'
  | 'visual-merchandising'
  | 'merchandising-buying'
  | 'wholesale-b2b'
  | 'crm-clienteling'
  | 'ecommerce-digital'
  | 'marketing-communication'
  | 'design-creation'
  | 'product-development-rd'
  | 'atelier-craft'
  | 'manufacturing-quality'
  | 'supply-chain-logistics'
  | 'finance'
  | 'hr-talent'
  | 'it-data'
  | 'legal-compliance'
  | 'strategy-management'
  | 'sustainability'
  | 'customer-service'
  | 'hospitality'
  | 'admin-facilities';

export type Seniority =
  | 'INTERNSHIP'
  | 'APPRENTICESHIP'
  | 'GRADUATE'
  | 'JUNIOR'
  | 'MID'
  | 'SENIOR'
  | 'MANAGER'
  | 'DIRECTOR'
  | 'EXECUTIVE';

export type FunctionDefinition = { key: JobFunction; label: string; family: JobFamily };

/** Le référentiel affiché : clé stable, libellé français, famille (retail / atelier / corporate). */
export const JOB_FUNCTIONS: ReadonlyArray<FunctionDefinition> = [
  { key: 'retail-client-advisor', label: 'Conseil de vente', family: 'retail' },
  { key: 'beauty-advisor', label: 'Conseil beauté', family: 'retail' },
  { key: 'retail-store-management', label: 'Direction de boutique', family: 'retail' },
  { key: 'retail-area-management', label: 'Direction régionale retail', family: 'retail' },
  { key: 'retail-operations', label: 'Opérations boutique & stock', family: 'retail' },
  { key: 'visual-merchandising', label: 'Visual merchandising', family: 'retail' },
  { key: 'merchandising-buying', label: 'Merchandising & achats', family: 'corporate' },
  { key: 'wholesale-b2b', label: 'Wholesale & B2B', family: 'corporate' },
  { key: 'crm-clienteling', label: 'CRM & clienteling', family: 'corporate' },
  { key: 'ecommerce-digital', label: 'E-commerce & digital', family: 'corporate' },
  { key: 'marketing-communication', label: 'Marketing & communication', family: 'corporate' },
  { key: 'design-creation', label: 'Création & design', family: 'corporate' },
  { key: 'product-development-rd', label: 'Développement produit & R&D', family: 'corporate' },
  { key: 'atelier-craft', label: 'Atelier & savoir-faire', family: 'craft' },
  { key: 'manufacturing-quality', label: 'Production & qualité', family: 'craft' },
  { key: 'supply-chain-logistics', label: 'Supply chain & logistique', family: 'corporate' },
  { key: 'finance', label: 'Finance', family: 'corporate' },
  { key: 'hr-talent', label: 'Ressources humaines', family: 'corporate' },
  { key: 'it-data', label: 'IT & data', family: 'corporate' },
  { key: 'legal-compliance', label: 'Juridique & conformité', family: 'corporate' },
  { key: 'strategy-management', label: 'Stratégie & direction', family: 'corporate' },
  { key: 'sustainability', label: 'Développement durable', family: 'corporate' },
  { key: 'customer-service', label: 'Service client', family: 'corporate' },
  { key: 'hospitality', label: 'Hôtellerie & restauration', family: 'corporate' },
  { key: 'admin-facilities', label: 'Administration & services généraux', family: 'corporate' },
];

export const SENIORITY_LABELS: Readonly<Record<Seniority, string>> = {
  INTERNSHIP: 'Stage',
  APPRENTICESHIP: 'Alternance',
  GRADUATE: 'Jeune diplômé · VIE · Graduate',
  JUNIOR: 'Junior',
  MID: 'Confirmé',
  SENIOR: 'Senior · Expert',
  MANAGER: 'Manager',
  DIRECTOR: 'Directeur',
  EXECUTIVE: 'Dirigeant',
};

const FAMILY_OF: Readonly<Record<JobFunction, JobFamily>> = Object.fromEntries(
  JOB_FUNCTIONS.map((f) => [f.key, f.family]),
) as Record<JobFunction, JobFamily>;

/** Majuscules sans accents, ponctuation aplatie : la forme sur laquelle les règles s'écrivent. */
export function comparableTitle(value: string | null | undefined): string {
  return (value ?? '')
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/[’'`]/g, "'")
    .replace(/[|/\\_+,;:()[\]{}<>«»"“”·•*]/g, ' ')
    // « Directeur.rice », « Assistant.e » : le point devant une marque de genre
    // devient un espace (jamais celui de « V.I.E. », protégé par la longueur du mot).
    .replace(/(?<=[A-Z]{3})\.(?=(?:E|ERE|EUSE|RICE|TRICE|SE|IVE|NE|IENNE|ICE|EUR|EURE|ES|EUSES|ERES)\b)/g, ' ')
    .replace(/\s+/g, ' ')
    // « Conseiller·ère », « Directeur.rice », « Assistant(e) » : la marque de
    // genre devient un mot isolé après aplatissement — on la retire.
    .replace(/\b([A-Z]{3,}) (?:E|ERE|EUSE|RICE|TRICE|SE|IVE|NE|IENNE|ICE|EUR|EURE|ES|EUSES|ERES)\b(?=\s|$)/g, '$1')
    .trim();
}

/**
 * Règles de métier, dans l'ordre : la première qui matche gagne, donc le plus
 * spécifique d'abord (« Visual Merchandiser » avant « Merchandiser », « Store
 * Manager » avant « Manager », « E-commerce Merchandiser » avant les deux).
 * Vocabulaire FR / EN / IT / ES / DE, celui des flux réels.
 */
const FUNCTION_RULES: ReadonlyArray<readonly [JobFunction, RegExp]> = [
  // — Retail : le cœur du secteur —
  ['visual-merchandising', /VISUAL MERCH|\bVM\b|WINDOW (DRESS|DISPLAY)|VITRINISTE|MERCHANDISING VISUEL|VISUAL DISPLAY|\bVISUAL\b(?! DESIGN)/],
  ['retail-area-management', /\b(AREA|REGIONAL|DISTRICT|CLUSTER|ZONE|MARKET|COUNTRY|TERRITORY) (SALES )?(MANAGER|DIRECTOR|LEAD(ER)?)\b|RETAIL (DIRECTOR|DIRECTEUR|DIRECTRICE)|(HEAD|DIRECTOR|DIRECTEUR|DIRECTRICE|VP|VICE PRESIDENT) OF RETAIL|DIRECTEUR RETAIL|DIRECTRICE RETAIL|RESPONSABLE (DE )?(REGION|SECTEUR|RESEAU)|MULTI[- ]?(STORE|SITE)|REGIONAL VISUAL|TRAVEL RETAIL (MANAGER|DIRECTOR)|DIRECT(EUR|RICE)\S* (REGIONAL|DE REGION|DE ZONE|RESEAU|DES VENTES)|RESPONSABLE\S* REGIONAL/],
  ['retail-store-management', /STORE (GENERAL )?(MANAGER|DIRECTOR|LEADER|SUPERVISOR|IN CHARGE)|BOUTIQUE (MANAGER|DIRECTOR|DIRECTEUR|DIRECTRICE|SUPERVISOR)|SHOP (MANAGER|SUPERVISOR|LEADER)|(RESPONSABLE\S*|DIRECTEUR|DIRECTRICE|ADJOINT\S*|GERANT\S*|ASSISTANT\S*) (DE |DU |D')?(BOUTIQUE|MAGASIN|POINT DE VENTE|CORNER|STAND|DEPARTEMENT|RAYON|SECTEUR CAISSE|PDV)|CHEF DE (BOUTIQUE|MAGASIN|RAYON|SECTEUR|DEPARTEMENT)|(DEPARTMENT|FLOOR|COUNTER|SALES|DEPUTY|ASSISTANT|CO-?|SHIFT|DUTY) MANAGER\b|(TEAM|SALES|SHIFT|FLOOR|SHOP|STORE) (LEAD(ER)?|SUPERVISOR|COORDINATOR)\b|SUPERVISOR\b|SUPERVISEUR|STORE DIRECTOR|STORE OPERATIONS MANAGER|RETAIL (STORE )?MANAGER|MANAGER (DE |DU )?(BOUTIQUE|MAGASIN)|CAPO NEGOZIO|STORE MANAGER|FILIALLEITER|RESPONSABLE ADJOINT|SECOND DE BOUTIQUE|SECOND DE MAGASIN|ASSISTANT MANAGER|MANAGER ADJOINT|GERENTE DE TIENDA|ENCARGAD|(DEPUTY )?HEAD OF (BOUTIQUE|STORE|SHOP)|MANAGER DES VENTES|BUTIK(S|K)?(S)?(CHEF|SJEF|LEDER|ANSVARLIG)|SCHICHTLEIT|FILIAAL(MANAGER|LEIDER)|WINKELMANAGER|KIEROWNIK|OUVERTURE FERMETURE|店长|店铺经理|店铺主管/],
  ['beauty-advisor', /BEAUTY (ADVISOR|CONSULTANT|ASSISTANT|ARTIST|EXPERT|SPECIALIST|AMBASSADOR|COACH|ASSOCIATE|STYLIST)|CONSEIL\S* BEAUTE|CONSEIL\S* (DE )?VENTE BEAUTE|MAKE[- ]?UP ARTIST|MAQUILLEU|ESTHETICIEN|BEAUTICIAN|SKIN ?CARE (ADVISOR|SPECIALIST|EXPERT|CONSULTANT)|FRAGRANCE (ADVISOR|SPECIALIST|EXPERT|CONSULTANT|AMBASSADOR)|COSMETIC (ADVISOR|CONSULTANT)|BEAUTY (SALES )?ASSOCIATE|CONSEILLE\S* (EN )?(PARFUMERIE|COSMETIQUE)|ANIMAT\S* (BEAUTE|MAQUILLAGE|PARFUM)|HAIR ?STYLIST|COIFFEU|NAIL TECH|ESTETISTA|KOSMETIKER|SPA THERAPIST|BROW (ARTIST|EXPERT)|SKIN ?CARE THERAPIST|MAKE ?UP (SPECIALIST|EXPERT|ADVISOR|CONSULTANT)|MAKE-?UP\S*|BEAUTY CONFID(A|E)NT|SKIN PRO\b|MAQUILLAGE|\bTHERAPIST\b|美容顾问|美容/],
  ['retail-operations', /STOCK (ASSOCIATE|ASSISTANT|CONTROLLER|COORDINATOR|SPECIALIST|KEEPER|CLERK|ROOM|MANAGER|HANDLER|OPERATIVE|SUPERVISOR|LEAD)|STOCKROOM|STOCKIST\S*|BACK ?OF ?HOUSE|\bBOH\b|INVENTORY (ASSOCIATE|CONTROL|SPECIALIST|COORDINATOR|CLERK|MANAGER|LEAD)|CASHIER|CAISSI|HOTE\S* DE CAISSE|HOST\S* (DE )?CAISSE|MAGASINIER\S* (DE |EN )?(BOUTIQUE|MAGASIN)|OPERATIONS (ASSOCIATE|ASSISTANT|SPECIALIST|COORDINATOR|SUPERVISOR|SUPPORT) ?(STORE|BOUTIQUE|RETAIL)?|RETAIL OPERATIONS|STORE OPERATIONS|BOUTIQUE OPERATIONS|LOSS PREVENTION|SECURITY (OFFICER|GUARD|AGENT)|AGENT DE SECURITE|VIGIL|RUNNER|GREETER|HOTE\S* D'ACCUEIL (BOUTIQUE|MAGASIN)|STORE (ASSISTANT|HOST|SUPPORT|RECEPTIONIST|ADMINISTRATOR)|EMPLOYE\S* (DE )?(MAGASIN|LIBRE[- ]SERVICE|POLYVALENT)|MISE EN RAYON|SALES SUPPORT|RETAIL ADMINISTRATOR|STOCK (TEAM|ADMIN)|CHARGE\S* (DE |DU )?STOCK|REPONEDOR|MAGAZZINIER|LAGERIST/],
  ['wholesale-b2b', /WHOLESALE|KEY ACCOUNT|\bKAM\b|\bB2B\b|EXPORT (MANAGER|SALES|AREA|COORDINATOR|ASSISTANT|EXECUTIVE|DIRECTOR)|TRAVEL RETAIL (MANAGER|DIRECTOR|EXECUTIVE|ACCOUNT|COORDINATOR|SALES (MANAGER|EXECUTIVE|DIRECTOR))|DUTY FREE (MANAGER|ACCOUNT|EXECUTIVE)|GRANDS COMPTES/],
  ['crm-clienteling', /\bCRM\b|CLIENTELING (MANAGER|SPECIALIST|COORDINATOR|EXECUTIVE|LEAD|DIRECTOR|PROJECT|ANALYST|ASSISTANT)|CLIENT (DEVELOPMENT|ENGAGEMENT|RELATION|LOYALTY|DATA|EXPERIENCE (MANAGER|LEAD|DIRECTOR|COORDINATOR))|LOYALTY|FIDELI[ST]|CUSTOMER (ENGAGEMENT|RELATIONSHIP|LOYALTY|DATA|INSIGHT|EXPERIENCE (MANAGER|LEAD|DIRECTOR|COORDINATOR|SPECIALIST))|\bVIC\b|VIP CLIENT|CLIENT MARKETING|RETENTION|LIFECYCLE MARKETING/],
  ['customer-service', /CUSTOMER (SERVICE|CARE|SUPPORT|RELATIONS|ADVISOR|ADVOCATE|SUCCESS|CONTACT)|CLIENT (SERVICE|CARE|SUPPORT|CENTER|CENTRE|CONTACT)(?! (ASSOCIATE|SPECIALIST|EXPERT|AMBASSADOR|CONSULTANT))|SERVICE CLIENT|RELATION CLIENT|CONSEILLE\S* (CLIENTELE |CLIENT )?(A DISTANCE|TELEPHON|EN LIGNE|E-?COMMERCE|DIGITAL|CENTRE D'APPEL|CALL CENTER)|CALL ?CENT|CONTACT ?CENT|CENTRE D'APPEL|TELECONSEIL|CHARGE\S* (DE )?CLIENTELE|AFTER[- ]?SALES|APRES[- ]VENTE|\bSAV\b|CONCIERGE|E-?CONCIERGE|CLIENT ADVISOR (REMOTE|DISTANCE|ONLINE|E-?COMMERCE|DIGITAL)|LIVE CHAT|CHAT ADVISOR|CARE (ADVISOR|SPECIALIST|AGENT)|ORDER MANAGEMENT|GESTION DES COMMANDES|CUSTOMER OPERATIONS|CUSTOMER EXPERIENCE (AGENT|ADVISOR|ASSOCIATE|SPECIALIST)|KUNDENSERVICE|KUNDENDIENST|ATENCION AL CLIENTE/],
  ['retail-client-advisor', /CLIENT ADVIS|CLIENT (SERVICE )?(ASSOCIATE|SPECIALIST|EXPERT|AMBASSADOR|CONSULTANT|EXPERIENCE (SPECIALIST|EXPERT|AMBASSADOR|ADVISOR|ASSOCIATE))|(SALES|RETAIL|STORE|BOUTIQUE|SHOP|FASHION|STYLE|WARDROBE|LUXURY|BRAND) (ADVISOR|ASSOCIATE|ASSISTANT|CONSULTANT|SPECIALIST|EXPERT|AMBASSADOR|STYLIST|PROFESSIONAL|ATTENDANT|EXECUTIVE|REPRESENTATIVE|EXPERT)|\bSALES\b(?! (MANAGER|DIRECTOR|OPERATIONS|PLANNING|ANALYST|SUPPORT|ADMIN|COORDINATOR|TRAINER))|CONSEILLE\S* (DE |EN |A LA )?(VENTE|CLIENTELE|MODE|BOUTIQUE|MAGASIN|COMMERCIAL)|CONSEILLE\S* (H F|F H)|\bVENDEU|VENDEDOR|VENDEDORA|VERKAUF|VERKÄUF|COMMESS[OAI]|ADDETT[OAI] (ALLA |ALLE )?VENDIT|SALES ?PERSON|SHOP ?ASSISTANT|STYLE ADVISOR|PERSONAL SHOPPER|PERSONAL STYLIST|BRAND AMBASSADOR|AMBASSADEU|DEMONSTRAT|ANIMAT\S* (DE |DES )?VENTE|KEY ?HOLDER|SENIOR SALES|SALES EXPERT|BOUTIQUE ASSISTANT|SHOP FLOOR|EQUIPIER|RETAIL ASSISTANT|RETAIL ASSOCIATE|OPTICIAN|OPTICIEN|VERKOOP|CHARGE\S* DES VENTES?|COLLABORATEU\S* (DE |DES )?VENTE|EMPLEAD\S* DE VENTAS|\bVENTAS\b|DEPENDIENT|AYUDANTE DE VENTA|ASSOCIAD\S* DE VENDAS|\bVENDAS\b|COLABORADOR\S* DE LOJA|\bLOJA\b|ASSISTENTE (ALLE |ALLA )?(VENDIT|CLIENTEL)|SPRZEDAWC|WINKELMEDEWERKER|VERKOOPMEDEWERKER|STORE MEDEWERKER|\bBUTIK|MEDARBE[JI]DER|UNGARBEJDER|EKSTRAHJELP|JULEHJELP|DELTIDS|STORE WORKER|TEAM MEMBER|EMPLOYE\S* DE RAYON|客户顾问|销售顾问|销售/],
  ['wholesale-b2b', /WHOLESALE|KEY ACCOUNT|\bKAM\b|ACCOUNT (MANAGER|EXECUTIVE|DIRECTOR)|BUSINESS DEVELOP|\bBIZ ?DEV\b|B2B|SALES (MANAGER|DIRECTOR|REPRESENTATIVE|EXECUTIVE|AGENT) ?(WHOLESALE|B2B|EXPORT|TRAVEL RETAIL|DISTRIBUT)|EXPORT (MANAGER|SALES|AREA|COORDINATOR|ASSISTANT)|COMMERCIAL (EXPORT|B2B|GRANDS COMPTES|SEDENTAIRE|TERRAIN|ITINERANT)|GRANDS COMPTES|DISTRIBUTOR MANAG|TRADE (MARKETING|SALES)|SHOWROOM|SALES (REP|AGENT)\b|VRP|TECHNICO-?COMMERCIAL|MEDICAL (REPRESENTATIVE|REP|SALES)|VISITEU\S* MEDICAL|CHARGE\S* D'AFFAIRES|INGENIEUR\S* COMMERCIAL|ATTACHE\S* COMMERCIAL|COMMERCIAL\b(?! ASSISTANT)|DUTY FREE|TRAVEL RETAIL/],
  // — Digital & commerce —
  ['ecommerce-digital', /E-?COMMERCE|ECOM\b|E-?SHOP|ONLINE (STORE|SHOP|SALES|MERCH|BUSINESS)|OMNI-?CHANNEL|DIGITAL (MANAGER|MARKETING|PROJECT|PRODUCT|EXPERIENCE|TRANSFORMATION|SPECIALIST|COORDINATOR|ANALYST|CONTENT|ACTIVATION|MERCH|STRATEG|BUSINESS|DIRECTOR|LEAD)|WEB ?(MERCH|MANAGER|PROJECT|MARKETING|DESIGNER|DEVELOPER|CONTENT)|SITE MERCH|MARKETPLACE|\bUX\b|\bUI\b|USER EXPERIENCE|PRODUCT OWNER|CONVERSION|\bCRO\b|\bSEO\b|\bSEA\b|\bSEM\b|PERFORMANCE MARKETING|GROWTH|TRAFFIC MANAGER|E-?BUSINESS|DIGITAL\b/],
  // — Fonctions corporate spécifiques au secteur —
  ['supply-chain-logistics', /SUPPLY ?CHAIN|LOGISTI|WAREHOUSE|ENTREPOT|MAGASINIER|PREPARAT\S* (DE )?COMMANDES?|ORDER (PICK|PREP|FULFIL|PROCESS)|PICK(ER|ING)\b|PACKER|CARISTE|FORKLIFT|TRANSPORT|SHIPPING|EXPEDITION|RECEPTION(?:NAIRE|NISTE)? (MARCHANDISE|LOGISTIQUE|ENTREPOT)|RECEIVING|IMPORT|EXPORT (OPERATIONS|COORDINATOR|SPECIALIST|COMPLIANCE)|CUSTOMS|DOUANE|DISTRIBUTION (CENTER|CENTRE)|\bDC\b|FULFIL|PLANIFICAT|(PRODUCTION|SUPPLY|DEMAND|MATERIAL|INVENTORY|CAPACITY|MASTER|LOGISTICS) PLANN|S&OP|PROCUREMENT|PURCHAS|ACHATS (INDIRECTS|GENERAUX|NON MARCHANDS)|INVENTORY (PLANN|ANALYST|MANAGER)|STOCK (PLANN|ANALYST|MANAGEMENT)|MATERIAL (PLANN|HANDL|COORDINATOR)|FLUX|FLOW MANAG|OPERATIONS (MANAGER|DIRECTOR|ANALYST|COORDINATOR|SPECIALIST)\b|CHAINE D'APPROVISIONNEMENT|APPROVISIONNEMENT|DELIVERY DRIVER|CHAUFFEUR|LIVREU|COURIER|GESTIONNAIRE DE STOCK|STOCK MANAGEMENT|3PL|FREIGHT|FORWARD|DISTRIBUTION PLANN|DEMAND (INTERN|ANALYST|MANAGER)/],
  ['merchandising-buying', /\bBUYER|\bBUYING|ACHETEU|\bACHATS?\b(?! (GENERAUX|INDIRECTS|NON MARCHANDS))|MERCHANDIS(ER|ING)(?! VISUEL)|MERCHANDISE (PLANN|ALLOCAT|CONTROL|MANAG)|\bMERCH\b|ALLOCAT(OR|ION)|PLANNER (RETAIL|MERCH|BUYING)|(RETAIL|MERCHANDISE|RANGE|ASSORTMENT|BUYING) PLANN|CATEGORY MANAG|COLLECTION (MERCH|PLANN|MANAG)|RANGE (MANAG|PLANN)|ASSORTMENT|PRODUCT MERCH|PRODUCT MANAGER|CHEF DE PRODUIT|CHEF\S* DE PRODUIT|PRODUCT LINE|APPROVISIONNEU|APPROVISIONNEMENT (RETAIL|BOUTIQUE)|SOURCING (MANAGER|SPECIALIST|COORDINATOR)/],
  ['marketing-communication', /MARKETING|COMMUNICATION|RESEAUX SOCIAUX|\bPR\b|PRESS|PRESSE|MEDIA|SOCIAL|CONTENT|CONTENU|BRAND (MANAGER|STRATEG|EXPERIENCE|ACTIVATION|COMMUNICATION|CONTENT|MARKETING|PARTNERSHIP)|CHEF DE MARQUE|INFLUENC|EVENT|EVENEMENT|COPYWRIT|REDACT|EDITOR|JOURNALIST|COMMUNITY|PARTNERSHIP|SPONSOR|ADVERTIS|PUBLICIT|CAMPAIGN|CREATIVE STRATEG|STORYTELL|PUBLIC RELATIONS|RELATIONS PUBLIQUES|MARKETING|ACTIVATION|PHOTOGRAPH|VIDEO|MOTION DESIGN|CELEBRIT|TALENT RELATION|CHARGE\S* DE COMMUNICATION|GRAPHIC DESIGN|GRAPHISTE|DA JUNIOR|ART DIRECTOR|DIRECT\S* ARTISTIQUE|DIRECTION ARTISTIQUE/],
  ['design-creation', /DESIGNER|DESIGN\b(?! ENGINEER)|STYLIST\b(?! ADVISOR)|STYLISTE|MODELISTE|PATTERN (MAKER|CUTTER|DESIGN)|CREATI(VE|F|VE DIRECTOR|ON)|STUDIO (ASSISTANT|MANAGER|COORDINATOR|DIRECTOR)|FASHION (DESIGN|ASSISTANT|STUDIO)|ILLUSTRAT|COLORIST|COLORISTE|TEXTILE (DESIGN|DEVELOP)|PRINT (DESIGN|DEVELOP)|KNITWEAR|MAILLE\b|ACCESSORIES DESIGN|JEWEL(RY|LERY) DESIGN|3D (DESIGN|ARTIST|MODEL)|CAD (DESIGN|ARTIST|OPERATOR)|\bCAO\b|DAO\b|ARCHITECT(?!URE (IT|SI|CLOUD|DATA|SOLUTION|TECHNIQUE|LOGICIEL))|ARCHITECTE (D'INTERIEUR|INTERIEUR|RETAIL)|INTERIOR DESIGN|STORE (DESIGN|PLANNING|DEVELOPMENT|CONCEPT)|CONCEPT (DESIGN|STORE)|VISUAL (DESIGN|IDENTITY)|GRAPHIC/],
  ['product-development-rd', /PRODUCT DEVELOP|DEVELOPPEMENT PRODUIT|DEVELOPPEU\S* PRODUIT|CHARGE\S* DE DEVELOPPEMENT|TECHNICAL DESIGN|GARMENT TECH|FIT TECH|TECHNICIEN\S* (PRODUIT|METHODE|DEVELOPPEMENT|PATRONAGE)|R ?& ?D\b|RESEARCH (AND|&) DEVELOP|RECHERCHE (ET|&) DEVELOP|FORMULAT|CHEMIST|CHIMISTE|SCIENTIST|SCIENTIFIQUE|LABORATO|\bLAB\b|REGULATORY|AFFAIRES REGLEMENTAIRES|REGLEMENTAIRE|TOXICOLOG|MICROBIOLOG|CLINICAL|EVALUATION (SENSORIELLE|PRODUIT)|PACKAGING (DEVELOP|ENGINEER|DESIGN|PROJECT)|INDUSTRIALISATION|INDUSTRIALIZATION|PROTOTYP|SAMPLE (DEVELOP|COORDINAT|ROOM)|MATERIAL(S)? (DEVELOP|RESEARCH|INNOVATION|SPECIALIST)|INNOVATION|PRODUCT (ENGINEER|TECHNOLOGIST|QUALITY|SPECIALIST|COORDINATOR|ASSISTANT)|BUREAU D'ETUDES|\bBE\b PRODUIT|COSTING|SAFETY ASSESSOR/],
  ['atelier-craft', /ARTISAN|CRAFTS?(MAN|WOMAN|PERSON|MAN)|COUTURI|SEAMSTRESS|SEWER|SEWING|TAILOR|TAILLEU|MACHINIST|PIQUEU|MECANICIEN\S* (EN )?CONFECTION|CONFECTION|OUVRI\S* (DE |D')?(PRODUCTION|CONFECTION|MAROQUINERIE|ATELIER|FABRICATION|COUTURE|SELLERIE|BIJOUTERIE|HORLOGERIE|FINITION)|OPERAT\S* (DE |EN |D')?(PRODUCTION|FABRICATION|CONFECTION|MAROQUINERIE|COUTURE|FINITION|MONTAGE|ASSEMBLAGE|CONDITIONNEMENT|POLISSAGE|SERTISSAGE)|ATELIER|WORKSHOP (ASSISTANT|MANAGER|TECHNICIAN|ARTISAN)|MAROQUIN|LEATHER (WORK|CRAFT|GOODS ARTISAN|ARTISAN)|SELLI|SADDLE|COUPEU|CUTTER\b|CUTTING (OPERATOR|TECHNICIAN|ROOM)|WATCHMAK|HORLOGE|OROLOGIA|UHRMACHER|JEWEL(L)?ER\b|JOAILLI|BIJOUTI|GOLDSMITH|ORFEVRE|GEMM?OLOG|POLISH|POLISSEU|SERTISS|STONE ?SETT|SETTER\b|ENGRAV|GRAVEU|EMBROID|BRODEU|BRODERIE|PLUMASSI|PLISS|MAILLEUR|TRICOT|KNITTER|WEAVER|TISSER|TANNER|TANNEU|SHOEMAK|CORDONNI|BOTTIER|FINISSEU|FINISHER|FINISHING (OPERATOR|TECHNICIAN|ARTISAN)|MONTEU|ASSEMBLEU|ASSEMBLER\b|CONTROLEU\S* (QUALITE )?(ATELIER|PRODUIT|CONFECTION)|REPAIR (TECHNICIAN|ARTISAN|SPECIALIST)|\bREPARAT|RETOUCH|ALTERATION|APPRENTI\S* (MAROQUIN|HORLOG|COUTUR|JOAILL|SELLI|TAILLEU)|MODELLISTA|SARTA|SARTO|CALZOLAI|PELLETTI|ARTIGIAN|TECHNICIEN\S* (HORLOG|QUALITE ATELIER|ATELIER)|GARMENT (MAKER|TECHNICIAN)|DRAPER|TOILISTE|PREMIERE D'ATELIER|CHEF D'ATELIER|RESPONSABLE D'ATELIER|WORKSHOP|METTEU\S* AU POINT|OPERAD\S* (DE )?PRODU/],
  ['manufacturing-quality', /PRODUCTION(?! PLANN)|MANUFACTUR|FABRICATION|\bUSINE|PLANT\b|FACTORY|INDUSTRI(AL|EL)|PROCESS (ENGINEER|TECHNICIAN|IMPROVEMENT)|MAINTENANCE|MAINTAIN|TECHNICIEN\S* (DE )?MAINTENANCE|MACHINE OPERATOR|OPERATOR\b|OPERATEU|CONDUCTEU\S* (DE )?(LIGNE|MACHINE|INSTALLATION)|QUALITY|QUALITE|\bQC\b|\bQA\b|\bHSE\b|\bEHS\b|\bSHE\b|SECURITE ENVIRONNEMENT|LEAN|CONTINUOUS IMPROVEMENT|AMELIORATION CONTINUE|METHODES|METHODS ENGINEER|CONDITIONNEMENT|PACKAGING OPERATOR|FILLING|REMPLISSAGE|PLANT MANAGER|DIRECTEUR D'USINE|RESPONSABLE DE PRODUCTION|CHEF D'EQUIPE PRODUCTION|TEAM LEADER PRODUCTION|SHIFT (LEADER|MANAGER) PRODUCTION|COMPOUND|PROCESS|MECHANIC\b|(?<!IT )(?<!SUPPORT )(?<!SERVICE )\bTECHNICIAN\b|LINE LEADER|TOOLROOM|MOU?LD MAKER|\d(ST|ND|RD) SHIFT|SAFETY (OFFICER|MANAGER|COORDINATOR)/],
  ['finance', /FINANC|ACCOUNT(ING|ANT)|COMPTAB|CONTROL(LER|LING|E DE GESTION)|CONTROLEU\S* DE GESTION|\bFP&A\b|TREASUR|TRESORER|\bTAX\b|FISCAL|AUDIT|CREDIT (ANALYST|CONTROL|MANAGER)|BILLING|FACTURATION|ACCOUNTS (PAYABLE|RECEIVABLE)|\bAP\b (SPECIALIST|CLERK|ANALYST)|\bAR\b (SPECIALIST|CLERK|ANALYST)|RECOUVREMENT|COLLECTIONS (ANALYST|SPECIALIST)|CONSOLIDATION|REPORTING (ANALYST|MANAGER|FINANC)|BUSINESS (CONTROL|ANALYST FINANC|PERFORMANCE)|PRICING|INVESTOR RELATION|\bM&A\b|CORPORATE FINANCE|PAYROLL ACCOUNT|ANALYSTE FINANCI|CHEF COMPTABLE|CASH|BUDGET|COST (CONTROL|ACCOUNT)|INTERNAL CONTROL|CONTROLE INTERNE|FACTURE/],
  ['hr-talent', /\bHR\b|\bRH\b|HUMAN RESOURCE|RESSOURCES HUMAINES|RECRUIT|RECRUT|TALENT (ACQUISITION|MANAG|DEVELOP|PARTNER|SOURC)|LEARNING|FORMATION|TRAINING|TRAINER|FORMATEU|\bL&D\b|PEOPLE (PARTNER|MANAGER|OPERATIONS|DIRECTOR|ANALYST|EXPERIENCE|TEAM)|HRBP|HR BUSINESS PARTNER|COMPENSATION|BENEFITS|\bC&B\b|PAYROLL|PAIE\b|PAYE\b|EMPLOYEE (RELATIONS|EXPERIENCE|ENGAGEMENT)|RELATIONS SOCIALES|LABOR RELATIONS|ORGANI[SZ]ATION(AL)? DEVELOP|WORKFORCE|STAFFING|ONBOARDING|CAMPUS|EMPLOYER BRAND|MARQUE EMPLOYEUR|DIVERSITY|INCLUSION|\bDEI\b|\bD&I\b|GESTIONNAIRE (DE )?(CARRIERES|PAIE|RH)|CHARGE\S* (DE |DES )?(RECRUTEMENT|RESSOURCES HUMAINES|RH|FORMATION|DEVELOPPEMENT RH)|COACH\b|ACADEMY|EDUCATION (MANAGER|SPECIALIST|EXECUTIVE|DIRECTOR)|EDUCAT(OR|RICE|EUR)|RETAIL (TRAINER|EDUCATION|LEARNING)|TALENT\b|EXECUTIVE SEARCH|\bRESEARCHER\b|PEOPLE (BUSINESS )?PARTNER|MEDECIN DU TRAVAIL|INFIRMI\S* (DU |D')?(TRAVAIL|ENTREPRISE)|OCCUPATIONAL HEALTH/],
  ['it-data', /\bIT\b|INFORMATI(ON TECHNOLOGY|QUE)|\bSI\b|SYSTEMES? D'INFORMATION|DATA|ANALYTICS|ANALYSTE (BI|DECISIONNEL)|\bBI\b|BUSINESS INTELLIGENCE|SOFTWARE|LOGICIEL|DEVELOP(ER|PEU)(?! PRODUIT)|ENGINEER\b(?! (PACKAGING|PRODUCT|PROCESS|QUALITY|MAINTENANCE|INDUSTRIAL|MANUFACTURING|R&D|MECHANICAL|ELECTRICAL|CIVIL|CHEMICAL|SALES))|INGENIEU\S* (LOGICIEL|INFORMATIQUE|DATA|SYSTEME|RESEAU|CLOUD|DEVOPS|IA|IT|SI|ETUDES ET DEVELOPPEMENT|DEVELOPPEMENT LOGICIEL)|PROGRAMM|FULL ?STACK|FRONT ?END|BACK ?END|DEVOPS|SRE\b|CLOUD|CYBER|SECURITY (ENGINEER|ANALYST|ARCHITECT|OFFICER|SPECIALIST)|INFOSEC|\bSOC\b|NETWORK|RESEAU\b(?!X? DE (BOUTIQUE|MAGASIN|DISTRIBUTION|VENTE))|INFRASTRUCTURE|SYSADMIN|SYSTEM(S)? (ADMIN|ENGINEER|ANALYST|ARCHITECT)|DATABASE|\bDBA\b|\bERP\b|\bSAP\b|SALESFORCE (DEVELOP|ADMIN|ARCHITECT|CONSULT|SPECIALIST)|\bCRM (DEVELOP|TECHNICAL|SYSTEM)|\bPLM\b|\bPOS\b (ENGINEER|SPECIALIST|SUPPORT|ANALYST)|TECH ?LEAD|TECHNICAL (LEAD|ARCHITECT|PRODUCT)|ARCHITECT(E)? (IT|SI|SOLUTION|CLOUD|DATA|TECHNIQUE|LOGICIEL|ENTREPRISE)|SOLUTION(S)? ARCHITECT|APPLICATION (MANAGER|SUPPORT|SPECIALIST|ANALYST|ENGINEER)|SUPPORT (TECHNIQUE|IT|INFORMATIQUE|APPLICATI)|HELP ?DESK|SERVICE DESK|TECHNICIEN\S* (INFORMATIQUE|SUPPORT|IT|HELPDESK|RESEAU|SYSTEME)|SCRUM|AGILE|\bQA (ENGINEER|AUTOMATION|TESTER)|TEST(ER|ING) (ENGINEER|ANALYST|AUTOMATION)|MACHINE LEARNING|\bML\b|\bAI\b|\bIA\b|\bCISO\b|ARTIFICIAL INTELLIGENCE|INTELLIGENCE ARTIFICIELLE|DATA SCIEN|\bETL\b|\bBIG DATA|DIGITAL WORKPLACE|OFFICE 365|MICROSOFT 365|CHEF DE PROJET (IT|SI|INFORMATIQUE|DIGITAL|TECHNIQUE|ERP|SAP|DATA)|PROJECT MANAGER (IT|ERP|SAP|DATA|TECH)|\bPMO\b IT|PRODUIT DIGITAL|INTEGRATION (SPECIALIST|ENGINEER|MANAGER)|AUTOMATION ENGINEER|ROBOTIC|\bRPA\b|WEB ?(DEVELOP|ENGINEER)|MOBILE (DEVELOP|ENGINEER)|IOS\b|ANDROID/],
  ['legal-compliance', /\bLEGAL\b|JURIDIQUE|JURIST|LAWYER|AVOCAT|COUNSEL\b|PARALEGAL|COMPLIANCE|CONFORMITE|\bIP\b|INTELLECTUAL PROPERTY|PROPRIETE INTELLECTUELLE|TRADEMARK|BRAND PROTECTION|ANTI-?COUNTERFEIT|CONTREFACON|PRIVACY|\bDPO\b|\bRGPD\b|\bGDPR\b|DATA PROTECTION|CONTRACT(S)? (MANAGER|SPECIALIST|ADMINISTRATOR)|CORPORATE (SECRETARY|GOVERNANCE)|ETHICS|ETHIQUE|RISK (MANAGER|ANALYST|OFFICER)|REGULATORY (COUNSEL|AFFAIRS LEGAL)|CUSTOMS COMPLIANCE|TRADE COMPLIANCE|INTERNAL AUDIT/],
  ['sustainability', /SUSTAINAB|DURABLE|\bCSR\b|\bRSE\b|\bESG\b|ENVIRONNEMENT(AL)?(?! HSE)|ENVIRONMENT(AL)?\b|CIRCULAR|CIRCULARIT|CLIMATE|CLIMAT\b|CARBON|CARBONE|IMPACT (MANAGER|ANALYST|LEAD|DIRECTOR)|RESPONSIBLE SOURCING|SOURCING RESPONSABLE|ETHICAL (SOURCING|TRADE)|TRACEABILIT|TRACABILIT|BIODIVERSIT|SOCIAL (COMPLIANCE|RESPONSIBILITY|IMPACT)|\bRSC\b|GREEN\b/],
  ['hospitality', /\bCHEF\b(?! DE (PROJET|PRODUIT|MARQUE|SECTEUR|RAYON|BOUTIQUE|MAGASIN|D'EQUIPE|VENTE|ZONE|REGION|DEPARTEMENT|CAISSE|GROUPE|MISSION|ATELIER))|CUISINI|COOK\b|PASTRY|PATISSI|SOMMELI|BARTEND|BARMAN|BARISTA|SERVEU|WAITER|WAITRESS|WAITING STAFF|RESTAURANT|HOTEL|HOUSEKEEP|GOUVERNANTE|BUTLER|MAJORDOME|VALET|FRONT DESK|FRONT OFFICE|GUEST (RELATION|EXPERIENCE|SERVICE)|SPA (MANAGER|RECEPTION|ATTENDANT)|MAITRE D'|COMMIS|PLONGEU|STEWARD|ROOM ATTENDANT|BANQUET|CATERING|TRAITEUR|HOSPITALITY|HEBERGEMENT|CONCIERGERIE|BELL(BOY|MAN)|BAGAGISTE|VOITURIER|RECEPTIONNISTE HOTEL|NIGHT AUDIT|F&B\b|FOOD (AND|&) BEVERAGE|LIFEGUARD|CLUB (MANAGER|HOST)|MEMBER(SHIP)? (MANAGER|EXPERIENCE)|SOUS ?CHEF|\bSERVER\b(?! (ADMIN|ENGINEER|SUPPORT))|\bCUOC|CAMARER|KELLNER|\bKOCH\b/],
  ['admin-facilities', /ASSISTANT\S* (DE )?DIRECTION|EXECUTIVE ASSISTANT|PERSONAL ASSISTANT|\bEA\b|\bPA\b TO|ADMINISTRATIVE|ADMINISTRATI(F|VE)|ASSISTANT\S* ADMINISTRATI|OFFICE (MANAGER|ASSISTANT|COORDINATOR|ADMINISTRATOR)|RECEPTION(IST|NISTE)?\b|STANDARD|ACCUEIL\b|FACILIT|SERVICES GENERAUX|GENERAL SERVICES|WORKPLACE|SECRETAR|TEAM ASSISTANT|ASSISTANT\S* (D'EQUIPE|POLYVALENT|DE GESTION)|MAILROOM|COURRIER|CHAUFFEUR PRIVE|DRIVER\b|TRAVEL (COORDINATOR|MANAGER)|FLEET|IMMOBILIER|REAL ESTATE|PROPERTY (MANAGER|DIRECTOR)|LEASE|CONSTRUCTION (MANAGER|PROJECT)|SITE MANAGER|BUILDING|MAINTENANCE (BATIMENT|BUILDING|FACILITIES)|ARCHIVIST|ARCHIVE|DOCUMENT CONTROL|GESTIONNAIRE ADMINISTRATI/],
  ['strategy-management', /STRATEG|\bCEO\b|\bCOO\b|\bCFO\b|\bCMO\b|\bCTO\b|\bCIO\b|\bCHRO\b|CHIEF\b|MANAGING DIRECTOR|DIRECTEUR\S* GENERAL|DIRECTRICE GENERALE|GENERAL MANAGER|GENERAL DIRECTOR|COUNTRY MANAGER|PRESIDENT|\bVP\b|VICE[- ]PRESIDENT|CHIEF OF STAFF|BUSINESS (ANALYST|MANAGER|PLANNING|OPERATIONS|TRANSFORMATION)|TRANSFORMATION|\bPMO\b|PROJECT (MANAGER|LEAD|COORDINATOR|DIRECTOR)|CHEF\S* DE PROJET|CHARGE\S* DE (PROJET|MISSION)|PROGRAM(ME)? (MANAGER|DIRECTOR|LEAD)|CONSULTANT|CONSEIL\b(?! (DE|EN|A) )|ANALYST\b|ANALYSTE\b|MANAGEMENT|DIRECTION (GENERALE|DES OPERATIONS)|HEAD OF (OPERATIONS|BUSINESS|STRATEGY|TRANSFORMATION)|EXCELLENCE|PERFORMANCE (MANAGER|ANALYST)|MARKET (INTELLIGENCE|RESEARCH|ANALYST)|INSIGHT|ETUDES (MARKETING|CONSOMMATEUR)|CONSUMER (INSIGHT|RESEARCH)|RETAIL EXCELLENCE|OPERATIONS EXCELLENCE|INTERIM (MANAGER|DIRECTOR)|FRANCHISE|LICENSING|LICENCE|DEVELOPPEMENT (INTERNATIONAL|RESEAU|RETAIL)|EXPANSION|NEW (STORE|MARKET) (OPENING|DEVELOPMENT)/],
  // — Dernier recours : un mot seul, quand rien de plus précis n'a parlé —
  ['retail-client-advisor', /\bADVISOR\b|\bCONSEILLE\S*\b|\bVENTE\b|\bVENDIT/],
];

/**
 * Le département, quand la source en publie un, lève l'ambiguïté d'un titre
 * muet (« Assistant », « Coordinator ») : la valeur est celle du vendeur,
 * mappée à la famille la plus proche.
 */
const DEPARTMENT_RULES: ReadonlyArray<readonly [JobFunction, RegExp]> = [
  ['visual-merchandising', /VISUAL/],
  ['retail-client-advisor', /^(RETAIL|SALES|STORE|BOUTIQUE|VENTE|SHOP|RETAIL SALES|RETAIL STORES?|STORES?|VENTE RETAIL)$/],
  ['crm-clienteling', /CRM|CLIENTELING|CLIENT (DEVELOPMENT|ENGAGEMENT)/],
  ['ecommerce-digital', /E-?COMMERCE|DIGITAL|ONLINE|OMNI/],
  ['merchandising-buying', /MERCH|BUYING|ACHAT|PLANNING/],
  ['wholesale-b2b', /WHOLESALE|B2B|TRAVEL RETAIL|EXPORT|COMMERCIAL/],
  ['marketing-communication', /MARKETING|COMMUNICATION|RESEAUX SOCIAUX|PRESS|MEDIA|\bPR\b|BRAND|CONTENT|EVENT/],
  ['design-creation', /DESIGN|CREATI|STUDIO|STYLE\b|COLLECTION/],
  ['product-development-rd', /PRODUCT DEVELOP|R ?& ?D|RESEARCH|DEVELOPPEMENT|SCIENTIFIC|REGULATORY|LABORAT|INNOVATION|PACKAGING/],
  ['atelier-craft', /ATELIER|WORKSHOP|CRAFT|MAROQUIN|HORLOG|JOAILL|COUTURE|SAVOIR/],
  ['manufacturing-quality', /PRODUCTION(?! PLANN)|MANUFACTUR|INDUSTRI|QUALIT|USINE|PLANT|MAINTENANCE|HSE|EHS/],
  ['supply-chain-logistics', /SUPPLY|LOGISTI|WAREHOUSE|ENTREPOT|PROCUREMENT|PURCHAS|OPERATIONS|DISTRIBUTION/],
  ['finance', /FINANC|ACCOUNT|COMPTAB|CONTROL|AUDIT|TAX|TREASUR/],
  ['hr-talent', /\bHR\b|\bRH\b|HUMAN|RESSOURCES HUMAINES|TALENT|PEOPLE|LEARNING|FORMATION|TRAINING|EDUCATION|RECRUIT/],
  ['it-data', /\bIT\b|INFORMATI|TECH|DATA|SYSTEM|DIGITAL TECH|SOFTWARE|ENGINEERING/],
  ['legal-compliance', /LEGAL|JURIDI|COMPLIANCE|\bIP\b/],
  ['sustainability', /SUSTAINAB|DURABLE|CSR|RSE|ESG|ENVIRONNEMENT|ENVIRONMENT/],
  ['customer-service', /CUSTOMER (SERVICE|CARE|SUPPORT)|SERVICE CLIENT|CLIENT SERVICE|CALL CENT|CONTACT CENT|AFTER SALES/],
  ['hospitality', /HOSPITALITY|HOTEL|RESTAURANT|F&B|FOOD/],
  ['admin-facilities', /ADMINISTRATI|FACILIT|OFFICE|GENERAL SERVICES|SERVICES GENERAUX|REAL ESTATE|IMMOBILIER/],
  ['strategy-management', /STRATEG|GENERAL MANAGEMENT|DIRECTION GENERALE|EXECUTIVE|CORPORATE|BUSINESS|MANAGEMENT|PROJECT/],
  ['retail-store-management', /STORE MANAGEMENT|RETAIL MANAGEMENT/],
  ['retail-operations', /STORE OPERATIONS|RETAIL OPERATIONS|STOCK/],
];

/** La famille de métier d'une offre, depuis son titre puis son département ; null si rien ne la nomme. */
export function classifyFunction(title: string | null | undefined, department?: string | null): JobFunction | null {
  const t = comparableTitle(title);
  if (t) {
    for (const [fn, re] of FUNCTION_RULES) if (re.test(t)) return fn;
  }
  const d = comparableTitle(department);
  if (d) {
    for (const [fn, re] of DEPARTMENT_RULES) if (re.test(d)) return fn;
  }
  return null;
}

export function familyOf(fn: JobFunction | null | undefined): JobFamily | null {
  return fn ? FAMILY_OF[fn] ?? null : null;
}

const INTERNSHIP_RE = /\bSTAGE\b|STAGIAIRE|INTERN(SHIP)?S?\b|TIROCIN|PRACTICAS|PRAKTIK|ESTAGIO|WERKSTUDENT|PLACEMENT (STUDENT|YEAR)|STUDENT PLACEMENT|\bSTUDENT\b/;
const APPRENTICESHIP_RE = /ALTERNAN|APPRENTI|APPRENTICE|APPRENTISSAGE|\bLEHRE\b|AUSBILDUNG|AZUBI|WORK[- ]STUDY|DUAL(ES)? (STUD|DEGREE)|CONTRAT (DE )?PRO(FESSIONNALISATION)?\b|LEARNERSHIP/;
const GRADUATE_RE = /GRADUATE|\bV\.?I\.?E\.?\b(?! )|\bVIE\b (?:\d|-|MISSION|PROGRAM|CONTRACT|[A-Z]{2,}\b)|TRAINEE|JEUNE\S* DIPLOM|EARLY CAREER|ROTATIONAL|NEOLAUREAT|MANAGEMENT TRAINING PROGRAM|\bMTP\b/;
const EXECUTIVE_RE = /\b[SE]?VP\b|VICE[- ]PRESIDENT|\bCHIEF\b|\bC[EFOMTIHR]O\b|\bCHRO\b|PRESIDENT|MANAGING DIRECTOR|DIRECTEUR\S* GENERAL|DIRECTRICE GENERALE|\bGENERAL MANAGER\b(?! (STORE|BOUTIQUE|ASSISTANT))|\bGM\b|AMMINISTRATORE DELEGATO|GESCHAFTSFUHRER|DIRECTOR GENERAL/;
const DIRECTOR_RE = /DIRECTOR|DIRECTEUR|DIRECTRICE|DIRETTOR|DIREKTOR|\bHEAD OF\b|\bHEAD\b,? |^HEAD\b|RESPONSABLE (DE |DU |DES )?(DEPARTEMENT|DIRECTION|POLE|BUSINESS UNIT|MARCHE|MARKET|REGION)|\bDIRECTION\b (?!ARTISTIQUE)/;
const MANAGER_RE = /MANAGER|MANAGEUR|RESPONSABLE|SUPERVIS|TEAM ?LEAD|CHEF D'EQUIPE|CHEF DE (BOUTIQUE|MAGASIN|RAYON|SECTEUR|DEPARTEMENT|ZONE|REGION|VENTE|CAISSE|GROUPE|ATELIER|SERVICE)|GERANT|CAPO\b|LEITER|LEITUNG|\bLEAD\b (?:OF|,)|COORDINAT(OR|EUR|RICE)|STORE IN CHARGE|PREMIERE? D'ATELIER|ENCARGAD|GERENTE|RESPONSABILE/;
/** Un « manager » qui ne manage pas : titre d'expertise individuelle. */
const IC_MANAGER_RE = /(PROJECT|PRODUCT|ACCOUNT|BRAND|COMMUNITY|CONTENT|CATEGORY|CAMPAIGN|EVENT|PARTNERSHIP|TRAFFIC|SOCIAL MEDIA|INFLUENCE|CRM|E-?COMMERCE|ECOM|MARKETING|COMMUNICATION|\bPR\b|PRESS|VISUAL MERCHANDISING|MERCHANDISE PLANNING|SUPPLY|DEMAND|PLANNING|QUALITY|QUALITE|MAINTENANCE|FACILIT|OFFICE|PAYROLL|TRAINING|LEARNING|EDUCATION|RECRUIT|SOURCING|LOGISTIC|TRANSPORT|CUSTOMS|COMPLIANCE|RISK|DATA|IT|SYSTEM|APPLICATION|SALESFORCE|SAP|ERP|CRM|PLM|SECURITY|SUSTAINABILITY|CSR|RSE|ESG|BUSINESS DEVELOPMENT|KEY ACCOUNT|WHOLESALE|EXPORT|TRADE|TERRITORY|REGIONAL SALES|CLIENT DEVELOPMENT|CLIENTELING|LOYALTY|TALENT|HR BUSINESS|PEOPLE|CHEF DE PROJET|CHEF DE PRODUIT|CHEF DE MARQUE|RESPONSABLE (DE |DU |DES )?(PROJET|PRODUIT|MARQUE|COMMUNICATION|MARKETING|CRM|E-?COMMERCE|DIGITAL|QUALITE|DEVELOPPEMENT|CLIENTELE|ZONE EXPORT|COMPTE|GRANDS COMPTES|FORMATION|RECRUTEMENT|PAIE|LOGISTIQUE|APPROVISIONNEMENT|PLANNING|SECURITE|MAINTENANCE|ADMINISTRATIF|COMPTABLE|CONTROLE|JURIDIQUE|RSE|DEVELOPPEMENT DURABLE)) (MANAGER|MANAGEUR)?/;
const SENIOR_RE = /\bSENIOR\b|\bSR\.?\b|CONFIRME|\bEXPERT\b|PRINCIPAL|\bLEAD\b|\bIII\b|\bIV\b|\bSPECIALIST\b|SPECIALISTE|STAFF (ENGINEER|DESIGNER)|ARCHITECT/;
const JUNIOR_RE = /\bJUNIOR\b|\bJR\.?\b|ENTRY[- ]LEVEL|DEBUTANT|\bASSISTANT\S*\b|\bASSOCIATE\b|\bI\b$|\bTRAINEE\b|AIDE\b|AUXILIAIRE|ADJOINT/;

/**
 * La séniorité, lue dans le titre puis dans le contrat normalisé. L'ordre des
 * tests fait la règle : « Stage – Assistant Manager » est un stage ; « Senior
 * Store Manager » est un manager ; « Senior Product Manager » est un senior
 * (un product manager ne manage pas d'équipe).
 */
export function classifySeniority(title: string | null | undefined, contract?: string | null): Seniority {
  const t = comparableTitle(title);
  if (INTERNSHIP_RE.test(t)) return 'INTERNSHIP';
  if (APPRENTICESHIP_RE.test(t)) return 'APPRENTICESHIP';
  if (GRADUATE_RE.test(t)) return 'GRADUATE';
  const byContract = normalizeContract(contract);
  if (byContract === 'STAGE') return 'INTERNSHIP';
  if (byContract === 'ALTERNANCE') return 'APPRENTICESHIP';
  if (byContract === 'VIE' || byContract === 'GRADUATE') return 'GRADUATE';
  if (EXECUTIVE_RE.test(t)) return 'EXECUTIVE';
  if (DIRECTOR_RE.test(t)) return 'DIRECTOR';
  if (MANAGER_RE.test(t) && !IC_MANAGER_RE.test(t)) return 'MANAGER';
  if (SENIOR_RE.test(t)) return 'SENIOR';
  if (JUNIOR_RE.test(t)) return 'JUNIOR';
  return 'MID';
}

/**
 * L'annonce parle-t-elle d'IA ? Sigles en capitales strictes — « AI » et
 * « IA » en minuscules sont des mots français (« j'ai », « il y a » n'y sont
 * pas mais « AI » après apostrophe dans un texte en capitales l'est) — plus
 * les expressions longues, toutes langues.
 */
const AI_ACRONYM_RE = /(?<!['’])\b(?:AI|IA|GENAI|LLMS?|NLP)\b(?![-']?\w)/;
const AI_PHRASE_RE = /artificial intelligence|intelligence artificielle|intelligenza artificiale|inteligencia artificial|k[üu]nstliche intelligenz|machine learning|apprentissage (automatique|machine)|deep learning|generative ai|gen ?ai\b|ia g[ée]n[ée]rative|large language model|computer vision|data scien|prompt engineer|\bcopilot\b|chatgpt|openai|neural network|r[ée]seaux? de neurones/i;

/**
 * Phrases qui parlent du PROCESSUS de recrutement, pas du poste : « refrain
 * from using AI tools during interviews », « artificial intelligence is not
 * used for hiring decisions ». Mesuré en prod (12 000 offres) : 2 700 mentions
 * « AI » dont l'immense majorité dans ces clauses — 18 % d'offres « IA » avant
 * ce filtre, contre ~1 % de vrais postes. Ces phrases sont retirées avant test.
 */
const PROCESS_SENTENCE_RE = /interview|entretien|recruit|recrut|hiring (process|decision|team|manager)|selection process|processus de (s[ée]lection|recrutement)|candidat|applicant|application(s)? (process|form|will|are|is)|assessment|fraud|scam|privacy|data protection|personal data|donn[ée]es personnelles|equal (opportunit|employment)|discriminat|accommodation|inteligencia artificial.{0,60}(entrevista|proceso)|refrain|abstenga|prohibit|not permitted|is not used|n'est pas utilis|sans utiliser|ne pas utiliser|disclos|consent|GDPR|RGPD|Bewerbung|Auswahl/i;

export function isAiRelated(title: string | null | undefined, description?: string | null): boolean {
  const body = (description ?? '')
    .slice(0, 30_000)
    .split(/(?<=[.!?])\s+|\n+|\s[•·▪●-]\s/)
    .filter((sentence) => !PROCESS_SENTENCE_RE.test(sentence))
    .join('\n');
  const text = `${title ?? ''}\n${body}`;
  return AI_PHRASE_RE.test(text) || AI_ACRONYM_RE.test(text);
}

export type JobClassification = {
  jobFunction: JobFunction | null;
  seniority: Seniority;
  isRetail: boolean | null;
  isAiRelated: boolean;
  skills: string[];
  taxonomyVersion: number;
};

/** Tout ce que la taxonomie écrit sur une offre, en une passe. */
export function classifyJob(input: {
  title: string | null | undefined;
  department?: string | null;
  description?: string | null;
  contract?: string | null;
}): JobClassification {
  const jobFunction = classifyFunction(input.title, input.department);
  const family = familyOf(jobFunction);
  return {
    jobFunction,
    seniority: classifySeniority(input.title, input.contract),
    isRetail: family === null ? null : family === 'retail',
    isAiRelated: isAiRelated(input.title, input.description),
    skills: extractSkills(`${input.title ?? ''}\n${input.description ?? ''}`),
    taxonomyVersion: TAXONOMY_VERSION,
  };
}
