import { readEmployment, type ProgramType } from './employment.js';
import { extractSkills } from './skills.js';

/**
 * Taxonomie Catwalks Intelligence (D38) : la famille de métier, la séniorité,
 * le caractère retail et le caractère IA d'une offre, classés à l'écriture
 * depuis ce que la source publie — le titre d'abord, le département ensuite.
 *
 * Une taxonomie du SECTEUR, pas « Sales / Marketing » : un Client Advisor, un
 * Store Manager, un Visual Merchandiser, un maroquinier et un horloger sont
 * des métiers distincts, et c'est cette finesse qui rend l'observatoire utile
 * à un DRH de Maison. Non classé = null, jamais deviné : la couverture est
 * affichée à côté de chaque chiffre.
 *
 * `TAXONOMY_VERSION` monte à chaque changement de règles : une offre dont la
 * version est en retard est re-classée à sa prochaine ré-attestation, et le
 * backfill `classify-jobs` rejoue toute la base.
 *
 * Version 2 (audit I-3, 2026-09-06, 2 × 300 offres jugées une par une) : les
 * coiffeurs de salon Ulta sortaient « Création & design » (4 357 offres, 71 %
 * de la famille), « Selling Associate » était un sellier, « Machine Learning
 * Engineer » des ressources humaines, un coordinateur un manager, un « Sales
 * Associate » un junior là où un « Conseiller de vente » était confirmé, et
 * l'indice IA comptait des clauses d'entreprise (« AI at Toast », « Altoona,
 * IA, USA »). Les règles ci-dessous portent chacune le titre qui l'a prouvée.
 */
export const TAXONOMY_VERSION = 2;

export type JobFamily = 'retail' | 'craft' | 'corporate';

export type JobFunction =
  | 'retail-client-advisor'
  | 'beauty-advisor'
  | 'retail-store-management'
  | 'retail-area-management'
  | 'retail-operations'
  | 'visual-merchandising'
  | 'merchandising-buying'
  | 'wholesale-b2b'
  | 'crm-clienteling'
  | 'ecommerce-digital'
  | 'marketing-communication'
  | 'design-creation'
  | 'product-development-rd'
  | 'atelier-craft'
  | 'manufacturing-quality'
  | 'supply-chain-logistics'
  | 'finance'
  | 'hr-talent'
  | 'it-data'
  | 'legal-compliance'
  | 'strategy-management'
  | 'sustainability'
  | 'customer-service'
  | 'hospitality'
  | 'admin-facilities';

/**
 * NIVEAUX de séniorité — et uniquement des niveaux.
 *
 * INTERNSHIP, APPRENTICESHIP et GRADUATE en ont été RETIRÉS le 2026-09-08 : ce
 * sont des DISPOSITIFS, pas des niveaux, et ils polluaient 4 296 offres. Ils
 * vivent désormais dans `programType`, dimension indépendante — un stagiaire
 * peut d'ailleurs être junior, et un participant à un graduate program aussi.
 */
export type Seniority =
  | 'JUNIOR'
  | 'MID'
  | 'SENIOR'
  | 'MANAGER'
  | 'DIRECTOR'
  | 'EXECUTIVE';

export type FunctionDefinition = { key: JobFunction; label: string; family: JobFamily };

/** Le référentiel affiché : clé stable, libellé français, famille (retail / atelier / corporate). */
export const JOB_FUNCTIONS: ReadonlyArray<FunctionDefinition> = [
  { key: 'retail-client-advisor', label: 'Conseil de vente', family: 'retail' },
  { key: 'beauty-advisor', label: 'Conseil beauté', family: 'retail' },
  { key: 'retail-store-management', label: 'Direction de boutique', family: 'retail' },
  { key: 'retail-area-management', label: 'Direction régionale retail', family: 'retail' },
  { key: 'retail-operations', label: 'Opérations boutique & stock', family: 'retail' },
  { key: 'visual-merchandising', label: 'Visual merchandising', family: 'retail' },
  { key: 'merchandising-buying', label: 'Merchandising & achats', family: 'corporate' },
  { key: 'wholesale-b2b', label: 'Wholesale & B2B', family: 'corporate' },
  { key: 'crm-clienteling', label: 'CRM & clienteling', family: 'corporate' },
  { key: 'ecommerce-digital', label: 'E-commerce & digital', family: 'corporate' },
  { key: 'marketing-communication', label: 'Marketing & communication', family: 'corporate' },
  { key: 'design-creation', label: 'Création & design', family: 'corporate' },
  { key: 'product-development-rd', label: 'Développement produit & R&D', family: 'corporate' },
  { key: 'atelier-craft', label: 'Atelier & savoir-faire', family: 'craft' },
  { key: 'manufacturing-quality', label: 'Production & qualité', family: 'craft' },
  { key: 'supply-chain-logistics', label: 'Supply chain & logistique', family: 'corporate' },
  { key: 'finance', label: 'Finance', family: 'corporate' },
  { key: 'hr-talent', label: 'Ressources humaines', family: 'corporate' },
  { key: 'it-data', label: 'IT & data', family: 'corporate' },
  { key: 'legal-compliance', label: 'Juridique & conformité', family: 'corporate' },
  { key: 'strategy-management', label: 'Stratégie & direction', family: 'corporate' },
  { key: 'sustainability', label: 'Développement durable', family: 'corporate' },
  { key: 'customer-service', label: 'Service client', family: 'corporate' },
  { key: 'hospitality', label: 'Hôtellerie & restauration', family: 'corporate' },
  { key: 'admin-facilities', label: 'Administration & services généraux', family: 'corporate' },
];

export const SENIORITY_LABELS: Readonly<Record<Seniority, string>> = {
  JUNIOR: 'Junior',
  MID: 'Confirmé',
  SENIOR: 'Senior · Expert',
  MANAGER: 'Manager',
  DIRECTOR: 'Directeur',
  EXECUTIVE: 'Dirigeant',
};

const FAMILY_OF: Readonly<Record<JobFunction, JobFamily>> = Object.fromEntries(
  JOB_FUNCTIONS.map((f) => [f.key, f.family]),
) as Record<JobFunction, JobFamily>;

/** Majuscules sans accents, ponctuation aplatie : la forme sur laquelle les règles s'écrivent. */
export function comparableTitle(value: string | null | undefined): string {
  return (value ?? '')
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/[’'`]/g, "'")
    // « informaticien∙ne », « Uhrmacher∙in » (point médian suisse), « Chef.fe » (Québec)
    .replace(/[∙·•]\s?(NE|IN|FE|E|ERE|RICE|TRICE|EUSE)\b/g, ' $1')
    .replace(/[|/\\_+,;:()[\]{}<>«»"“”·•*]/g, ' ')
    // « Directeur.rice », « Assistant.e » : le point devant une marque de genre
    // devient un espace (jamais celui de « V.I.E. », protégé par la longueur du mot).
    .replace(/(?<=[A-Z]{3})\.(?=(?:E|ERE|EUSE|RICE|TRICE|SE|IVE|NE|IENNE|ICE|EUR|EURE|ES|EUSES|ERES|FE|IN)\b)/g, ' ')
    .replace(/\s+/g, ' ')
    // « Conseiller·ère », « Directeur.rice », « Assistant(e) » : la marque de
    // genre devient un mot isolé après aplatissement — on la retire.
    .replace(/\b([A-Z]{3,}) (?:E|ERE|EUSE|RICE|TRICE|SE|IVE|NE|IENNE|ICE|EUR|EURE|ES|EUSES|ERES|FE|IN)\b(?=\s|$)/g, '$1')
    .trim();
}

/**
 * Règles de métier, dans l'ordre : la première qui matche gagne, donc le plus
 * spécifique d'abord. Le bloc de tête porte les mots qui ne trompent jamais
 * (un joaillier, un contrôleur de gestion, un ingénieur machine learning) :
 * ils tranchent avant les mots ambigus (« sales », « manager », « learning »).
 * Vocabulaire FR / EN / IT / ES / DE / NL / DK / PL / ZH, celui des flux réels.
 */
const FUNCTION_RULES: ReadonlyArray<readonly [JobFunction, RegExp]> = [
  // — Mots qui ne trompent jamais —
  ['visual-merchandising', /VISUAL MERCH|\bVM\b|WINDOW (DRESS|DISPLAY)|VITRINISTE|MERCHANDISING VISUEL|VISUAL DISPLAY|\bVISUAL\b(?! DESIGN)/],
  // « Joaillier SAV », « Incastonatore », « Sculpteur », « Spécialiste métier Polissage », « Constructeur mouvement » (audit I-3)
  ['atelier-craft', /^(?!.*\b(?:CHEF DE PRODUIT|PRODUCT|MANAGER|BUYER|ACHETEU|DEVELOP|MERCHANDIS|MARKETING|PROJECT|PROJET|DESIGNER|DIRECT\S*|RESPONSABLE\S*|ASSISTANT\S*|CATEGORY|PLANNER|SOURCING|COORDINAT\S*|ANALYST|CONSULTANT|CHARGE\S*|HEAD|SALES|ADVISOR|VENDEU\S*|CONSEILLE\S*|SUPERVISOR|CONTROLLER|CONTROLEU\S*|ENGINEER|INGENIEU\S*|SPECIALIST|EXPERT|AMBASSADOR|TRAINER|FORMATEU\S*|EXECUTIVE)\b).*(?:JOAILLI|BIJOUTI|HORLOGE|OROLOGIA|UHRMACHER|WATCHMAK|MAROQUIN|SELLIER|SELLERIE|SERTISS|STONE ?SETT|INCASTONAT|POLISS|POLISHER|SCULPT|COUTURI|SEAMSTRESS|BRODEU|EMBROID|GOLDSMITH|ORFEVRE|GEMM?OLOG|ADDETT[OAI] (AL TAGLIO|ALLA PREPARAZIONE)|CONSTRUCTEUR (DE )?MOUVEMENT|GAREU|GUNMAKER|MOULAGE|EBARBAGE|METTEU\S* AUX? (POINT|BAIN)|ARTISAN|ARTIGIAN|CRAFTS?(MAN|WOMAN|PERSON)|ATELIER|WORKSHOP)/],
  // « Machine Learning Engineer », « Data Scientist », « Data Engineer STAGE TALENT DAY », « Enterprise Architecture - AI & Data », « Informaticien » (audit I-3)
  ['it-data', /MACHINE LEARNING|\bML\b (ENGINEER|OPS|SCIENTIST)|MLOPS|DATA (SCIEN|ENGINEER|ARCHITECT|ANALYST|ANALYTICS|PLATFORM|GOVERNANCE|PRODUCT)|\bBIG DATA|\bAI\b|\bIA\b(?! GENERALE)|ARTIFICIAL INTELLIGENCE|INTELLIGENCE ARTIFICIELLE|SOFTWARE (ENGINEER|DEVELOP|ARCHITECT|QUALITY)|\bDEVOPS\b|\bSRE\b|CYBER|INFORMATICIEN|SEMANTIC|FULL ?STACK|FRONT ?END|BACK ?END|TECH(NOLOGY)? (TEAM )?LEAD|SITE RELIABILITY|CLOUD (ENGINEER|ARCHITECT)|SALESFORCE (DEVELOP|ADMIN|ARCHITECT|TECHNOLOGY|SUPPORT)|SOLUTIONS? ARCHITECT|ARCHITECT.*(SYSTEM|\bIT\b|DATA|CLOUD|SOFTWARE|ENTERPRISE|INTEGRATION|SALESFORCE|\bSAP\b)/],
  // « Contrôleur de gestion industriel », « Manufacturing Project Controller », « Trésorier Groupe », « Account Payable Trainee » (audit I-3)
  ['finance', /CONTROLEU\S* DE GESTION|PROJECT CONTROLLER|\bCONTROLLER\b|CONTROLLING\b|TRESORI|TRESORER|TREASUR|ACCOUNTS? PAYABLE|ACCOUNTS? RECEIVABLE|COMPTAB|\bFP&A\b|\bTAX\b|FISCAL/],
  // « Senior Manager, Legal Operations and Innovation » (audit I-3)
  ['legal-compliance', /\bLEGAL\b|JURIDIQUE|JURISTE|LAWYER|AVOCAT|COUNSEL\b|PARALEGAL|COMPLIANCE|CONFORMITE|INTELLECTUAL PROPERTY|PROPRIETE INTELLECTUELLE|BRAND PROTECTION|ANTI-?COUNTERFEIT|CONTREFACON|\bDPO\b|\bRGPD\b|\bGDPR\b/],
  // « Restaurant Host - Marketplace Café », « Crew Member Kitchen », « Barista, Ralph's Coffee », « Restaurant Supervisor » (audit I-3)
  ['hospitality', /RESTAURANT|\bCAFE\b|COFFEE|KITCHEN|CUISINE(?! CARE)|CUISINI|\bCOOK\b|PASTRY|PATISSI|SOMMELI|BARTEND|BARMAN|BARISTA|SERVEU|WAITER|WAITRESS|WAITING STAFF|\bHOTEL\b|HOUSEKEEP|GOUVERNANTE|BUTLER|MAJORDOME|FRONT DESK|GUEST (RELATION|EXPERIENCE|SERVICE)|MAITRE D'|COMMIS DE|PLONGEU|STEWARD|ROOM ATTENDANT|BANQUET|CATERING|TRAITEUR|HOSPITALITY|CONCIERGERIE|BELL(BOY|MAN)|VOITURIER|NIGHT AUDIT|F&B\b|FOOD (AND|&) BEVERAGE|SOUS[- ]CHEF|CHEF DE PARTIE|\bCHEF\b(?! (?:DE (?:PROJET|PRODUIT|MARQUE|SECTEUR|RAYON|BOUTIQUE|MAGASIN|VENTE|ZONE|REGION|DEPARTEMENT|CAISSE|GROUPE|MISSION|SERVICE|COLLECTION|LIGNE)|D'EQUIPE|D'ATELIER))|\bCUOC|CAMARER|KELLNER|\bKOCH\b|\bSERVER\b(?! (ADMIN|ENGINEER|SUPPORT))/],
  // « Client Contact Consultant, E-Commerce », « E-Boutique Client Advisor », « Client Success Representative » (audit I-3)
  ['customer-service', /CUSTOMER (SERVICE|CARE|SUPPORT|RELATIONS|ADVISOR|ADVOCATE|SUCCESS|CONTACT)|CLIENT (SERVICE|CARE|SUPPORT|CENTER|CENTRE|CONTACT|SUCCESS)(?! (ASSOCIATE|SPECIALIST|EXPERT|AMBASSADOR))|SERVICE CLIENT|RELATION CLIENT|CONSEILLE\S* (CLIENTELE |CLIENT )?(A DISTANCE|TELEPHON|EN LIGNE|E-?COMMERCE|DIGITAL|CENTRE D'APPEL|CALL CENTER)|CALL ?CENT|CONTACT ?CENT|CENTRE D'APPEL|TELECONSEIL|CHARGE\S* (DE )?CLIENTELE|AFTER[- ]?SALES|APRES[- ]VENTE|\bSAV\b|CONCIERGE\b|E-?CONCIERGE|CLIENT ADVISOR (REMOTE|DISTANCE|ONLINE|E-?COMMERCE|DIGITAL)|E-?BOUTIQUE (CLIENT|ADVISOR|ASSISTANT)|LIVE CHAT|CHAT ADVISOR|CARE (ADVISOR|SPECIALIST|AGENT)|ORDER MANAGEMENT|GESTION DES COMMANDES|CUSTOMER OPERATIONS|CUSTOMER EXPERIENCE (AGENT|ADVISOR|ASSOCIATE|SPECIALIST)|KUNDENSERVICE|KUNDENDIENST|ATENCION AL CLIENTE/],
  // « Regional Online Retail Director », « Online Retail Operations Coordinator », « Operations Supervisor ECommerce » (audit I-3)
  ['ecommerce-digital', /E-?COMMERCE|ECOM\b|E-?SHOP|E-?RETAIL|ONLINE (RETAIL|STORE|SHOP|SALES|MERCH|BUSINESS)|OMNI-?CHANNEL|MARKETPLACE(?! CAFE)|SITE MERCH|WEB ?MERCH/],
  // « B2B Operations Specialist », « National Field Force Manager », « Global Sales Director », « Travel Retail Sales Executive » (audit I-3)
  ['wholesale-b2b', /\bB2B\b|WHOLESALE|KEY ACCOUNT|\bKAM\b|FIELD FORCE|EXPORT (MANAGER|SALES|AREA|COORDINATOR|ASSISTANT|EXECUTIVE|DIRECTOR)|TRAVEL RETAIL (MANAGER|DIRECTOR|EXECUTIVE|ACCOUNT|COORDINATOR|SALES (MANAGER|EXECUTIVE|DIRECTOR))|DUTY FREE (MANAGER|ACCOUNT|EXECUTIVE)|GRANDS COMPTES|SALES DIRECTOR|MEDICAL (REPRESENTATIVE|REP|SALES)|VISITEU\S* MEDICAL|TERRITORY (ACCOUNT|SALES) (EXECUTIVE|MANAGER|REP)|ACCOUNT EXECUTIVE|BUSINESS DEVELOP/],
  // « Senior Manager, Client Experience », « Clienteling Product Management Intern », « Client Treatment Manager », « Stage - Assistant(e) Clienteling International » (audit I-3)
  ['crm-clienteling', /\bCRM\b|CLIENTELING\b|CLIENT TREATMENT|EXPERIENCE CLIENT\b|CLIENT EXPERIENCE (MANAGER|LEAD|DIRECTOR|COORDINATOR|ASSISTANT|INTERN|PROJECT|STRATEG)|MANAGER,? CLIENT EXPERIENCE|CLIENT (DEVELOPMENT|ENGAGEMENT|RELATION|LOYALTY|DATA|INSIGHTS?)|LOYALTY|FIDELI[ST]|CUSTOMER (ENGAGEMENT|RELATIONSHIP|LOYALTY|DATA|INSIGHT)|\bVIC\b|VIP CLIENT|CLIENT MARKETING|RETENTION|LIFECYCLE MARKETING/],
  // « STAGE - Assistant(e) Sales Merchandiser », « Directrice de Collection », « MD Manager », « Planner » (audit I-3)
  ['merchandising-buying', /SALES MERCHANDIS|MERCHANDISE PLANN|DIRECT(EUR|RICE)\S* DE COLLECTION|RESPONSABLE\S* DE (COLLECTION|LIGNE PRODUIT)|^MD MANAGER|^PLANNER$|ASSISTANT PLANNER/],
  // « Acheteur Indirect », « Gestionnaire d'ordonnancement », « Strategic Sourcing Manager » (audit I-3)
  ['supply-chain-logistics', /ACHETEU\S* (INDIRECT|HORS PRODUCTION)|ACHATS (INDIRECTS|GENERAUX|NON MARCHANDS)|ORDONNANCEMENT|STRATEGIC SOURCING/],
  // « Assistant Manager, Network Development » : le réseau de boutiques, pas l'informatique (audit I-3)
  ['strategy-management', /NETWORK DEVELOPMENT|STORE NETWORK|NETWORK (EXPANSION|PLANNING)|DEVELOPPEMENT (DU )?RESEAU|NEW STORE OPENING/],
  // — Retail : le cœur du secteur —
  ['retail-area-management', /\b(AREA|REGIONAL|DISTRICT|CLUSTER|ZONE|MARKET|COUNTRY|TERRITORY) (SALES )?(MANAGER|DIRECTOR|LEAD(ER)?)\b|RETAIL (DIRECTOR|DIRECTEUR|DIRECTRICE)|(HEAD|DIRECTOR|DIRECTEUR|DIRECTRICE|VP|VICE PRESIDENT) OF RETAIL|DIRECTEUR RETAIL|DIRECTRICE RETAIL|RESPONSABLE (DE )?(REGION|SECTEUR|RESEAU)|MULTI[- ]?(STORE|SITE)|REGIONAL VISUAL|TRAVEL RETAIL (MANAGER|DIRECTOR)|DIRECT(EUR|RICE)\S* (REGIONAL|DE REGION|DE ZONE|RESEAU|DES VENTES)|RESPONSABLE\S* REGIONAL/],
  // « TEAM MANAGER », « Storemanager », « Assistent Shopmanager », « Responsable des Ventes », « Responsável de Turno », « Souschef » (Normal, danois), « Directeur adjoint » (audit I-3)
  // Un superviseur d'ENTREPÔT n'est pas un directeur de boutique : la règle
  // retail ci-dessous contient un `SUPERVISOR` isolé qui attrapait « Warehouse
  // Supervisor », « Distribution Centre Team Leader », « Superviseur Logistique »
  // (19 offres mesurées en prod le 2026-09-07). Cette garde passe AVANT elle.
  ['supply-chain-logistics', /(WAREHOUSE|ENTREPOT|ENTREPÔT|LOGISTI|DISTRIBUTION (CENTER|CENTRE)?|SUPPLY ?CHAIN|FULFILMENT|FULFILLMENT)[^|]*?(SUPERVISOR|SUPERVISEUR|TEAM ?LEAD|LEAD\b|MANAGER|RESPONSABLE)|(SUPERVISOR|SUPERVISEUR|TEAM ?LEAD(ER)?|SHIFT LEAD|FLOOR SUPERVISOR)[^|]*?(WAREHOUSE|ENTREPOT|ENTREPÔT|LOGISTIQUE|LOGISTICS|DISTRIBUTION|SUPPLY ?CHAIN)/],
  ['retail-store-management', /STORE ?(GENERAL )?(MANAGER|DIRECTOR|LEADER|SUPERVISOR|IN CHARGE)|BOUTIQUE (MANAGER|DIRECTOR|DIRECTEUR|DIRECTRICE|SUPERVISOR)|SHOP ?(MANAGER|SUPERVISOR|LEADER)|(RESPONSABLE\S*|DIRECTEUR|DIRECTRICE|ADJOINT\S*|GERANT\S*|ASSISTANT\S*) (DE |DU |D')?(BOUTIQUE|MAGASIN|POINT DE VENTE|CORNER|STAND|DEPARTEMENT|RAYON|SECTEUR CAISSE|PDV)|CHEF DE (BOUTIQUE|MAGASIN|RAYON|SECTEUR|DEPARTEMENT)|(DEPARTMENT|FLOOR|COUNTER|SALES|DEPUTY|ASSISTANT|CO-?|SHIFT|DUTY) MANAGER\b(?!,)|(TEAM|SALES|SHIFT|FLOOR|SHOP|STORE) (LEAD(ER)?|SUPERVISOR)\b|^TEAM MANAGER|SUPERVISOR\b|SUPERVISEUR|RETAIL (STORE )?MANAGER|MANAGER (DE |DU )?(BOUTIQUE|MAGASIN)|CAPO NEGOZIO|FILIALLEITER|RESPONSABLE ADJOINT|SECOND DE BOUTIQUE|SECOND DE MAGASIN|ASSISTANT MANAGER\b(?!,)|MANAGER ADJOINT|GERENTE DE TIENDA|ENCARGAD|(DEPUTY )?HEAD OF (BOUTIQUE|STORE|SHOP)|MANAGER DES VENTES|RESPONSABLE\S* (DES VENTES|RETAIL|DE TURNO)|RESPONSAVEL DE TURNO|BUTIK(S|K)?(S)?(CHEF|SJEF|LEDER|ANSVARLIG)|SCHICHTLEIT|FILIAAL(MANAGER|LEIDER)|WINKELMANAGER|KIEROWNIK|OUVERTURE FERMETURE|SOUSCHEF|CHEF D'EQUIPE(?! (PRODUCTION|LOGISTIQUE|ENTREPOT|ATELIER))|DIRECT(EUR|RICE)\S* ADJOINT|店长|店铺经理|店铺主管/],
  // « Master Stylist », « Elite Stylist », « Brow Waxing Expert », « Specialty Artist - MAC », « Lead Piercer », « Szépségtanácsadó » (audit I-3)
  ['beauty-advisor', /BEAUTY (ADVISOR|CONSULTANT|ASSISTANT|ARTIST|EXPERT|SPECIALIST|AMBASSADOR|COACH|ASSOCIATE|STYLIST)|CONSEIL\S* BEAUTE|CONSEIL\S* (DE )?VENTE BEAUTE|MAKE[- ]?UP ARTIST|MAQUILLEU|ESTHETICIEN|BEAUTICIAN|SKIN ?CARE (ADVISOR|SPECIALIST|EXPERT|CONSULTANT)|FRAGRANCE (ADVISOR|SPECIALIST|EXPERT|CONSULTANT|AMBASSADOR)|COSMETIC (ADVISOR|CONSULTANT)|CONSEILLE\S* (EN )?(PARFUMERIE|COSMETIQUE)|ANIMAT\S* (BEAUTE|MAQUILLAGE|PARFUM)|HAIR ?STYLIST|HAIR ?DRESS|COIFFEU|NAIL TECH|ESTETISTA|KOSMETIKER|SPA THERAPIST|BROW|\bLASH|WAX(ING)? (EXPERT|SPECIALIST|ARTIST)|PIERC|SKIN ?CARE THERAPIST|MAKE ?UP (SPECIALIST|EXPERT|ADVISOR|CONSULTANT)|MAKE-?UP\S*|BEAUTY CONFID(A|E)NT|SKIN PRO\b|SKIN (SPECIALIST|EXPERT|THERAPIST)|MAQUILLAGE|\bTHERAPIST\b|(MASTER|ELITE|SENIOR|LEAD) STYLIST|SPECIALTY ARTIST|RETAIL ARTIST|SZEPSEGTANACSADO|美容顾问|美容/],
  // « Task Associate », « Seasonal Retail Stock », « Full Time Operation Associate », « Boutique Administrator », « Stock Executive », « Cajeros/as », « Operations Leader », « Asset Protection Investigator », « Guest Coordinator » (audit I-3)
  ['retail-operations', /STOCK (ASSOCIATE|ASSISTANT|CONTROLLER|COORDINATOR|SPECIALIST|KEEPER|CLERK|ROOM|MANAGER|HANDLER|OPERATIVE|SUPERVISOR|LEAD|EXECUTIVE|TEAM|ADMIN)|STOCKROOM|STOCKIST\S*|BACK ?OF ?HOUSE|\bBOH\b|BACK[- ]?OFFICE|INVENTORY (ASSOCIATE|CONTROL|SPECIALIST|COORDINATOR|CLERK|MANAGER|LEAD)|CASHIER|CAISSI|CAJER|HOTE\S* DE CAISSE|HOST\S* (DE )?CAISSE|MAGASINIER\S* (DE |EN )?(BOUTIQUE|MAGASIN)|OPERATIONS? (ASSOCIATE|ASSISTANT|SPECIALIST|COORDINATOR|SUPERVISOR|SUPPORT|LEADER) ?(STORE|BOUTIQUE|RETAIL)?|RETAIL OPERATIONS|STORE OPERATIONS|BOUTIQUE (OPERATIONS|ADMIN\S*|OFFICE)|LOSS PREVENTION|ASSET PROTECTION|RISK ASSOCIATE|SECURITY (OFFICER|GUARD|AGENT)|AGENT DE SECURITE|VIGIL|RUNNER|GREETER|GUEST COORDINATOR|HOTE\S* D'ACCUEIL (BOUTIQUE|MAGASIN)|STORE (ASSISTANT|HOST|SUPPORT|RECEPTIONIST|ADMINISTRATOR)|EMPLOYE\S* (DE )?(MAGASIN|LIBRE[- ]SERVICE|POLYVALENT)|MISE EN RAYON|SALES SUPPORT|RETAIL ADMINISTRATOR|CHARGE\S* (DE |DU )?STOCK|AGENT DE STOCK|RETAIL STOCK|REPLENISH|REPONEDOR|MAGAZZINIER|LAGERIST|^TASK\b|TASK (ASSOCIATE|LEAD|MANAGER)|COORDINAT\S* STOCK/],
  // « Stylist 16 hours », « Full-Time Stylist (Bloomingdales) », « Selling Associate », « Athlete III », « Kundenberater », « Weihnachtsaushilfe », « Temporary Associate », « Retail Experience Intern », « Welcome Host » (audit I-3)
  ['retail-client-advisor', /CLIENT ADVIS|CLIENT (SERVICE )?(ASSOCIATE|SPECIALIST|EXPERT|AMBASSADOR|CONSULTANT|EXPERIENCE (SPECIALIST|EXPERT|AMBASSADOR|ADVISOR|ASSOCIATE))|(SALES|RETAIL|STORE|BOUTIQUE|SHOP|FASHION|STYLE|WARDROBE|LUXURY|BRAND) (ADVISOR|ASSOCIATE|ASSISTANT|CONSULTANT|SPECIALIST|EXPERT|AMBASSADOR|STYLIST|PROFESSIONAL|ATTENDANT|EXECUTIVE|REPRESENTATIVE|EXPERT)|\bSALES\b(?! (MANAGER|DIRECTOR|OPERATIONS|PLANNING|ANALYST|SUPPORT|ADMIN|COORDINATOR|TRAINER))|SELLING (ASSOCIATE|SPECIALIST|SUPERVISOR|PROFESSIONAL|LEAD|ASSISTANT)|\bSTYLIST\b.*\b(HOURS|HRS|PART[- ]TIME|FULL[- ]TIME|BLOOMINGDALES|OUTLET|STORE|MALL)\b|STYLIST\s*SALES|CONSEILLE\S* (DE |EN |A LA )?(VENTE|CLIENTELE|MODE|BOUTIQUE|MAGASIN|COMMERCIAL)|CONSEILLE\S* (H F|F H)|\bVENDEU|VENDEDOR|VENDEDORA|VERKAUF|VERKÄUF|COMMESS[OAI]|ADDETT[OAI] (ALLA |ALLE )?VENDIT|SALES ?PERSON|SHOP ?ASSISTANT|STYLE ADVISOR|PERSONAL SHOPPER|PERSONAL STYLIST|BRAND AMBASSADOR|AMBASSADEU|DEMONSTRAT|ANIMAT\S* (DE |DES )?VENTE|KEY ?HOLDER|SENIOR SALES|SALES EXPERT|BOUTIQUE ASSISTANT|SHOP FLOOR|EQUIPIER|RETAIL ASSISTANT|RETAIL ASSOCIATE|OPTICIAN|OPTICIEN|VERKOOP|CHARGE\S* DES VENTES?|COLLABORATEU\S* (DE |DES )?VENTE|EMPLEAD\S* DE VENTAS|\bVENTAS\b|DEPENDIENT|AYUDANTE DE VENTA|ASSOCIAD\S* DE VENDAS|\bVENDAS\b|COLABORADOR\S* DE LOJA|\bLOJA\b|ASSISTENTE (ALLE |ALLA )?(VENDIT|CLIENTEL)|SPRZEDAWC|DORADC|WINKELMEDEWERKER|VERKOOPMEDEWERKER|STORE MEDEWERKER|\bBUTIK|MEDARBE[JI]DER|UNGARBEJDER|EKSTRAHJELP|JULEHJELP|DELTIDS|STORE WORKER|TEAM MEMBER|EMPLOYE\S* DE RAYON|\bATHLETE\b|KUNDENBERAT|AUSHILFE|CUSTOMER (HOST|ASSISTANT)|^(TEMPORARY |SEASONAL |FULL TIME |PART TIME |PT |FT |CASUAL )?ASSOCIATE( I{1,3})?$|BECARI|RETAIL (EXPERIENCE|TRAINEE|GENERATION|INTERN)|JEWELL?ERY (EXPERT|ADVISOR|CONSULTANT)|WELCOME HOST|נציג|매장 직원|販売|客户顾问|销售顾问|销售/],
  // Le reste du commercial : après le retail, pour ne pas y avaler un vendeur.
  ['wholesale-b2b', /ACCOUNT (MANAGER|EXECUTIVE|DIRECTOR)|\bBIZ ?DEV\b|SALES (MANAGER|DIRECTOR|REPRESENTATIVE|EXECUTIVE|AGENT) ?(WHOLESALE|B2B|EXPORT|TRAVEL RETAIL|DISTRIBUT)|COMMERCIAL (EXPORT|B2B|GRANDS COMPTES|SEDENTAIRE|TERRAIN|ITINERANT)|DISTRIBUTOR MANAG|TRADE (MARKETING|SALES)|SHOWROOM|SALES (REP|AGENT)\b|VRP|TECHNICO-?COMMERCIAL|CHARGE\S* D'AFFAIRES|INGENIEUR\S* COMMERCIAL|ATTACHE\S* COMMERCIAL|COMMERCIAL\b(?! ASSISTANT)|DUTY FREE|TRAVEL RETAIL/],
  // — Le reste du corporate —
  ['ecommerce-digital', /ONLINE|DIGITAL (MANAGER|MARKETING|PROJECT|PRODUCT|EXPERIENCE|TRANSFORMATION|SPECIALIST|COORDINATOR|ANALYST|CONTENT|ACTIVATION|MERCH|STRATEG|BUSINESS|DIRECTOR|LEAD)|WEB ?(MANAGER|PROJECT|MARKETING|DESIGNER|DEVELOPER|CONTENT|MASTER)|\bUX\b|\bUI\b|USER EXPERIENCE|PRODUCT OWNER|CONVERSION|\bCRO\b|\bSEO\b|\bSEA\b|\bSEM\b|PERFORMANCE MARKETING|GROWTH|TRAFFIC MANAGER|E-?BUSINESS|DIGITAL\b/],
  ['merchandising-buying', /\bBUYER|\bBUYING|ACHETEU|\bACHATS?\b|MERCHANDIS(ER|ING)(?! VISUEL)|MERCHANDISE (ALLOCAT|CONTROL|MANAG)|\bMERCH\b|ALLOCAT(OR|ION)|PLANNER (RETAIL|MERCH|BUYING)|(RETAIL|MERCHANDISE|RANGE|ASSORTMENT|BUYING) PLANN|CATEGORY MANAG|COLLECTION (MERCH|PLANN|MANAG)|RANGE (MANAG|PLANN)|ASSORTMENT|PRODUCT MERCH|PRODUCT MANAGER|CHEF DE PRODUIT|CHEF\S* DE PRODUIT|PRODUCT LINE|APPROVISIONNEU|APPROVISIONNEMENT (RETAIL|BOUTIQUE)|SOURCING (MANAGER|SPECIALIST|COORDINATOR)/],
  // « PR Assistant Manager », « Coordinator, Promotions » (audit I-3)
  ['marketing-communication', /MARKETING|COMMUNICATION|RESEAUX SOCIAUX|\bPR\b|PRESS|PRESSE|MEDIA|SOCIAL|CONTENT|CONTENU|BRAND (MANAGER|STRATEG|EXPERIENCE|ACTIVATION|COMMUNICATION|CONTENT|MARKETING|PARTNERSHIP|STORYTELL)|CHEF DE MARQUE|INFLUENC|EVENT|EVENEMENT|COPYWRIT|REDACT|EDITOR|JOURNALIST|COMMUNITY|PARTNERSHIP|SPONSOR|ADVERTIS|PUBLICIT|CAMPAIGN|CREATIVE STRATEG|STORYTELL|PUBLIC RELATIONS|RELATIONS PUBLIQUES|ACTIVATION|PHOTOGRAPH|VIDEO|MOTION DESIGN|CELEBRIT|TALENT RELATION|CHARGE\S* DE COMMUNICATION|GRAPHIC DESIGN|GRAPHISTE|DA JUNIOR|ART DIRECTOR|DIRECT\S* ARTISTIQUE|DIRECTION ARTISTIQUE|PROMOTIONS?\b/],
  // « Développeur Peaux Précieuses », « Directeur Développement Matières », « Ingénieur développement technique » (audit I-3)
  ['product-development-rd', /DEVELOPPEU\S* (PEAUX|MATIERE|CUIR|PRODUIT)|DEVELOPPEMENT (MATIERE|TECHNIQUE|PRODUIT)|PRODUCT DEVELOP|CHARGE\S* DE DEVELOPPEMENT|TECHNICAL DESIGN|GARMENT TECH|FIT TECH|TECHNICIEN\S* (PRODUIT|METHODE|DEVELOPPEMENT|PATRONAGE)|R ?& ?D\b|RESEARCH (AND|&) DEVELOP|RECHERCHE (ET|&) DEVELOP|FORMULAT|CHEMIST|CHIMISTE|SCIENTIST|SCIENTIFIQUE|LABORATO|\bLAB\b|REGULATORY|AFFAIRES REGLEMENTAIRES|REGLEMENTAIRE|TOXICOLOG|MICROBIOLOG|CLINICAL|EVALUATION (SENSORIELLE|PRODUIT)|PACKAGING (DEVELOP|ENGINEER|DESIGN|PROJECT)|INDUSTRIALISATION|INDUSTRIALIZATION|PROTOTYP|SAMPLE (DEVELOP|COORDINAT|ROOM)|MATERIAL(S)? (DEVELOP|RESEARCH|INNOVATION|SPECIALIST)|INNOVATION|PRODUCT (ENGINEER|TECHNOLOGIST|QUALITY|SPECIALIST|COORDINATOR|ASSISTANT)|BUREAU D'ETUDES|\bBE\b PRODUIT|COSTING|SAFETY ASSESSOR/],
  ['design-creation', /DESIGNER|DESIGN\b(?! ENGINEER)|STYLIST\b(?! ADVISOR)|STYLISTE|MODELISTE|PATTERN (MAKER|CUTTER|DESIGN)|CREATI(VE|F|VE DIRECTOR|ON)|STUDIO (ASSISTANT|MANAGER|COORDINATOR|DIRECTOR)|FASHION (DESIGN|ASSISTANT|STUDIO)|ILLUSTRAT|COLORIST|COLORISTE|TEXTILE (DESIGN|DEVELOP)|PRINT (DESIGN|DEVELOP)|KNITWEAR|MAILLE\b|ACCESSORIES DESIGN|JEWEL(RY|LERY) DESIGN|3D (DESIGN|ARTIST|MODEL)|CAD (DESIGN|ARTIST|OPERATOR)|\bCAO\b|DAO\b|ARCHITECT(?!URE (IT|SI|CLOUD|DATA|SOLUTION|TECHNIQUE|LOGICIEL))|ARCHITECTE (D'INTERIEUR|INTERIEUR|RETAIL)|INTERIOR DESIGN|STORE (DESIGN|PLANNING|DEVELOPMENT|CONCEPT)|CONCEPT (DESIGN|STORE)|VISUAL (DESIGN|IDENTITY)|GRAPHIC/],
  ['atelier-craft', /MACHINIST|PIQUEU|MECANICIEN\S* (EN )?CONFECTION|CONFECTION|OUVRI\S* (DE |D')?(PRODUCTION|CONFECTION|MAROQUINERIE|ATELIER|FABRICATION|COUTURE|SELLERIE|BIJOUTERIE|HORLOGERIE|FINITION)|OPERAT\S* (DE |EN |D')?(PRODUCTION|FABRICATION|CONFECTION|MAROQUINERIE|COUTURE|FINITION|MONTAGE|ASSEMBLAGE|CONDITIONNEMENT|POLISSAGE|SERTISSAGE)|LEATHER (WORK|CRAFT|GOODS ARTISAN|ARTISAN)|SADDLE|COUPEU|CUTTER\b|CUTTING (OPERATOR|TECHNICIAN|ROOM)|JEWEL(L)?ER\b|ENGRAV|GRAVEU|BRODERIE|PLUMASSI|PLISS|MAILLEUR|TRICOT|KNITTER|WEAVER|TISSER|TANNER|TANNEU|SHOEMAK|CORDONNI|BOTTIER|FINISSEU|FINISHER|FINISHING (OPERATOR|TECHNICIAN|ARTISAN)|MONTEU|ASSEMBLEU|ASSEMBLER\b|CONTROLEU\S* (QUALITE )?(ATELIER|PRODUIT|CONFECTION)|REPAIR (TECHNICIAN|ARTISAN|SPECIALIST)|\bREPARAT|RETOUCH|ALTERATION|TAILOR|TAILLEU|SEWER|SEWING|MODELLISTA|SARTA|SARTO|CALZOLAI|PELLETTI|TECHNICIEN\S* (HORLOG|QUALITE ATELIER|ATELIER)|GARMENT (MAKER|TECHNICIAN)|DRAPER|TOILISTE|PREMIERE D'ATELIER|CHEF D'ATELIER|RESPONSABLE D'ATELIER|OPERAD\S* (DE )?PRODU|MASCHINENBEDIENER|WERKZEUGMECHANIKER/],
  // « Cleaning Technician » → services généraux, pas la production (audit I-3)
  ['admin-facilities', /CLEANING|NETTOYAGE|AGENT D'ENTRETIEN|\bCLEANER\b/],
  ['manufacturing-quality', /PRODUCTION(?! PLANN)|MANUFACTUR|FABRICATION|\bUSINE|PLANT\b|FACTORY|INDUSTRI(AL|EL)|PROCESS (ENGINEER|TECHNICIAN|IMPROVEMENT)|MAINTENANCE|MAINTAIN|TECHNICIEN\S* (DE )?MAINTENANCE|MACHINE OPERATOR|OPERATOR\b|OPERATEU|CONDUCTEU\S* (DE )?(LIGNE|MACHINE|INSTALLATION)|QUALITY|QUALITE|QUALITA\b|\bQC\b|\bQA\b|\bHSE\b|\bEHS\b|\bSHE\b|SECURITE ENVIRONNEMENT|LEAN|CONTINUOUS IMPROVEMENT|AMELIORATION CONTINUE|METHODES|METHODS ENGINEER|CONDITIONNEMENT|PACKAGING OPERATOR|FILLING|REMPLISSAGE|PLANT MANAGER|DIRECTEUR D'USINE|RESPONSABLE DE PRODUCTION|CHEF D'EQUIPE PRODUCTION|TEAM LEADER PRODUCTION|SHIFT (LEADER|MANAGER) PRODUCTION|COMPOUND|PROCESS|MECHANIC\b|(?<!IT )(?<!SUPPORT )(?<!SERVICE )\bTECHNICIAN\b|LINE LEADER|TOOLROOM|MOU?LD MAKER|\d(ST|ND|RD) SHIFT|SAFETY (OFFICER|MANAGER|COORDINATOR)/],
  ['supply-chain-logistics', /SUPPLY ?CHAIN|LOGISTI|WAREHOUSE|ENTREPOT|MAGASINIER|PREPARAT\S* (DE )?COMMANDES?|ORDER (PICK|PREP|FULFIL|PROCESS)|PICK(ER|ING)\b|PACKER|CARISTE|FORKLIFT|TRANSPORT|SHIPPING|EXPEDITION|RECEPTION(?:NAIRE|NISTE)? (MARCHANDISE|LOGISTIQUE|ENTREPOT)|RECEIVING|IMPORT|EXPORT (OPERATIONS|COORDINATOR|SPECIALIST|COMPLIANCE)|CUSTOMS|DOUANE|DISTRIBUTION (CENTER|CENTRE)|\bDC\b|FULFIL|PLANIFICAT|(PRODUCTION|SUPPLY|DEMAND|MATERIAL|INVENTORY|CAPACITY|MASTER|LOGISTICS|DISTRIBUTION) PLANN|S&OP|PROCUREMENT|PURCHAS|INVENTORY (PLANN|ANALYST|MANAGER)|STOCK (PLANN|ANALYST|MANAGEMENT)|MATERIAL (PLANN|HANDL|COORDINATOR)|FLUX|FLOW MANAG|OPERATIONS (MANAGER|DIRECTOR|ANALYST|COORDINATOR|SPECIALIST)\b|CHAINE D'APPROVISIONNEMENT|APPROVISIONNEMENT|DELIVERY DRIVER|CHAUFFEUR|LIVREU|COURIER|GESTIONNAIRE DE STOCK|STOCK MANAGEMENT|3PL|FREIGHT|FORWARD|DEMAND (INTERN|ANALYST|MANAGER)/],
  ['finance', /FINANC|ACCOUNT(ING|ANT)|CONTROL(LER|LING|E DE GESTION)|AUDIT|CREDIT (ANALYST|CONTROL|MANAGER)|BILLING|FACTURATION|FACTURE|RECOUVREMENT|COLLECTIONS (ANALYST|SPECIALIST)|CONSOLIDATION|REPORTING (ANALYST|MANAGER|FINANC)|BUSINESS (CONTROL|ANALYST FINANC|PERFORMANCE)|PRICING|INVESTOR RELATION|\bM&A\b|CORPORATE FINANCE|PAYROLL ACCOUNT|ANALYSTE FINANCI|CHEF COMPTABLE|CASH|BUDGET|COST (CONTROL|ACCOUNT)|INTERNAL CONTROL|CONTROLE INTERNE/],
  // « People & Culture In-Store Business Partner » ; « TALENT DAY » (Cartier) n'est pas un poste RH (audit I-3)
  ['hr-talent', /\bHR\b|\bRH\b|HUMAN RESOURCE|RESSOURCES HUMAINES|RECRUIT|RECRUT|TALENT (ACQUISITION|MANAG|DEVELOP|PARTNER|SOURC)|LEARNING|FORMATION|TRAINING|TRAINER|FORMATEU|\bL&D\b|PEOPLE (PARTNER|MANAGER|OPERATIONS|DIRECTOR|ANALYST|EXPERIENCE|TEAM|(&|AND) CULTURE|BUSINESS PARTNER)|HRBP|HR BUSINESS PARTNER|COMPENSATION|BENEFITS|\bC&B\b|PAYROLL|PAIE\b|PAYE\b|EMPLOYEE (RELATIONS|EXPERIENCE|ENGAGEMENT)|RELATIONS SOCIALES|LABOR RELATIONS|ORGANI[SZ]ATION(AL)? DEVELOP|WORKFORCE|STAFFING|ONBOARDING|CAMPUS|EMPLOYER BRAND|MARQUE EMPLOYEUR|DIVERSITY|INCLUSION|\bDEI\b|\bD&I\b|GESTIONNAIRE (DE )?(CARRIERES|PAIE|RH)|CHARGE\S* (DE |DES )?(RECRUTEMENT|RESSOURCES HUMAINES|RH|FORMATION|DEVELOPPEMENT RH)|COACH\b|ACADEMY|EDUCATION (MANAGER|SPECIALIST|EXECUTIVE|DIRECTOR)|EDUCAT(OR|RICE|EUR)|RETAIL (TRAINER|EDUCATION|LEARNING)|TALENT\b(?! DAY)|EXECUTIVE SEARCH|\bRESEARCHER\b|MEDECIN DU TRAVAIL|INFIRMI\S* (DU |D')?(TRAVAIL|ENTREPRISE)|OCCUPATIONAL HEALTH/],
  ['it-data', /\bIT\b|INFORMATI(ON TECHNOLOGY|QUE)|\bSI\b|SYSTEMES? D'INFORMATION|DATA|ANALYTICS|ANALYSTE (BI|DECISIONNEL)|\bBI\b|BUSINESS INTELLIGENCE|SOFTWARE|LOGICIEL|DEVELOP(ER|PEU)(?! PRODUIT)|ENGINEER\b(?! (PACKAGING|PRODUCT|PROCESS|QUALITY|MAINTENANCE|INDUSTRIAL|MANUFACTURING|R&D|MECHANICAL|ELECTRICAL|CIVIL|CHEMICAL|SALES))|INGENIEU\S* (LOGICIEL|INFORMATIQUE|DATA|SYSTEME|RESEAU|CLOUD|DEVOPS|IA|IT|SI|ETUDES ET DEVELOPPEMENT|DEVELOPPEMENT LOGICIEL)|PROGRAMM|CLOUD|SECURITY (ENGINEER|ANALYST|ARCHITECT|OFFICER|SPECIALIST)|INFOSEC|\bSOC\b|NETWORK|RESEAU\b(?!X? DE (BOUTIQUE|MAGASIN|DISTRIBUTION|VENTE))|INFRASTRUCTURE|SYSADMIN|SYSTEM(S)? (ADMIN|ENGINEER|ANALYST|ARCHITECT)|DATABASE|\bDBA\b|\bERP\b|\bSAP\b|SALESFORCE|\bCRM (DEVELOP|TECHNICAL|SYSTEM)|\bPLM\b|\bPOS\b (ENGINEER|SPECIALIST|SUPPORT|ANALYST)|TECHNICAL (LEAD|ARCHITECT|PRODUCT)|ARCHITECT(E)? (IT|SI|SOLUTION|CLOUD|DATA|TECHNIQUE|LOGICIEL|ENTREPRISE)|SOLUTION(S)? ARCHITECT|APPLICATION (MANAGER|SUPPORT|SPECIALIST|ANALYST|ENGINEER)|SUPPORT (TECHNIQUE|IT|INFORMATIQUE|APPLICATI)|HELP ?DESK|SERVICE DESK|TECHNICIEN\S* (INFORMATIQUE|SUPPORT|IT|HELPDESK|RESEAU|SYSTEME)|SCRUM|AGILE|\bQA (ENGINEER|AUTOMATION|TESTER)|TEST(ER|ING) (ENGINEER|ANALYST|AUTOMATION)|\bETL\b|DIGITAL WORKPLACE|OFFICE 365|MICROSOFT 365|CHEF DE PROJET (IT|SI|INFORMATIQUE|DIGITAL|TECHNIQUE|ERP|SAP|DATA)|PROJECT MANAGER (IT|ERP|SAP|DATA|TECH)|\bPMO\b IT|PRODUIT DIGITAL|INTEGRATION (SPECIALIST|ENGINEER|MANAGER)|AUTOMATION ENGINEER|ROBOTIC|\bRPA\b|WEB ?(DEVELOP|ENGINEER)|MOBILE (DEVELOP|ENGINEER)|IOS\b|ANDROID|\bCISO\b/],
  ['sustainability', /SUSTAINAB|DURABLE|\bCSR\b|\bRSE\b|\bESG\b|ENVIRONNEMENT(AL)?(?! HSE)|ENVIRONMENT(AL)?\b|CIRCULAR|CIRCULARIT|CLIMATE|CLIMAT\b|CARBON|CARBONE|IMPACT (MANAGER|ANALYST|LEAD|DIRECTOR)|RESPONSIBLE SOURCING|SOURCING RESPONSABLE|ETHICAL (SOURCING|TRADE)|TRACEABILIT|TRACABILIT|BIODIVERSIT|SOCIAL (COMPLIANCE|RESPONSIBILITY|IMPACT)|\bRSC\b|GREEN\b/],
  ['admin-facilities', /ASSISTANT\S* (DE )?DIRECTION|EXECUTIVE ASSISTANT|PERSONAL ASSISTANT|\bEA\b|\bPA\b TO|ADMINISTRATIVE|ADMINISTRATI(F|VE)|ASSISTANT\S* ADMINISTRATI|OFFICE (MANAGER|ASSISTANT|COORDINATOR|ADMINISTRATOR)|RECEPTION(IST|NISTE)?\b|STANDARD|ACCUEIL\b|FACILIT|SERVICES GENERAUX|GENERAL SERVICES|WORKPLACE|SECRETAR|TEAM ASSISTANT|ASSISTANT\S* (D'EQUIPE|POLYVALENT|DE GESTION)|MAILROOM|COURRIER|CHAUFFEUR PRIVE|DRIVER\b|TRAVEL (COORDINATOR|MANAGER)|FLEET|IMMOBILIER|REAL ESTATE|PROPERTY (MANAGER|DIRECTOR)|LEASE|CONSTRUCTION (MANAGER|PROJECT)|SITE MANAGER|BUILDING|MAINTENANCE (BATIMENT|BUILDING|FACILITIES)|ARCHIVIST|ARCHIVE|DOCUMENT CONTROL|GESTIONNAIRE ADMINISTRATI/],
  ['strategy-management', /STRATEG|\bCEO\b|\bCOO\b|\bCFO\b|\bCMO\b|\bCTO\b|\bCIO\b|\bCHRO\b|CHIEF\b|MANAGING DIRECTOR|DIRECTEUR\S* GENERAL|DIRECTRICE GENERALE|GENERAL MANAGER|GENERAL DIRECTOR|COUNTRY MANAGER|PRESIDENT|\bVP\b|VICE[- ]PRESIDENT|CHIEF OF STAFF|BUSINESS (ANALYST|MANAGER|PLANNING|OPERATIONS|TRANSFORMATION)|TRANSFORMATION|\bPMO\b|PROJECT (MANAGER|LEAD|COORDINATOR|DIRECTOR)|CHEF\S* DE PROJET|CHARGE\S* DE (PROJET|MISSION)|PROGRAM(ME)? (MANAGER|DIRECTOR|LEAD)|CONSULTANT|CONSEIL\b(?! (DE|EN|A) )|ANALYST\b|ANALYSTE\b|MANAGEMENT|DIRECTION (GENERALE|DES OPERATIONS)|HEAD OF (OPERATIONS|BUSINESS|STRATEGY|TRANSFORMATION)|EXCELLENCE|PERFORMANCE (MANAGER|ANALYST)|MARKET (INTELLIGENCE|RESEARCH|ANALYST)|INSIGHT|ETUDES (MARKETING|CONSOMMATEUR)|CONSUMER (INSIGHT|RESEARCH)|RETAIL EXCELLENCE|OPERATIONS EXCELLENCE|INTERIM (MANAGER|DIRECTOR)|FRANCHISE|LICENSING|LICENCE|DEVELOPPEMENT (INTERNATIONAL|RESEAU|RETAIL)|EXPANSION|NEW (STORE|MARKET) (OPENING|DEVELOPMENT)/],
  // — Dernier recours : un mot seul, quand rien de plus précis n'a parlé —
  ['retail-client-advisor', /\bADVISOR\b|\bCONSEILLE\S*\b|\bVENTE\b|\bVENDIT|\bRETAIL\b/],
];

/**
 * Le département, quand la source en publie un, lève l'ambiguïté d'un titre
 * muet (« Assistant », « Coordinator ») : la valeur est celle du vendeur,
 * mappée à la famille la plus proche.
 */
const DEPARTMENT_RULES: ReadonlyArray<readonly [JobFunction, RegExp]> = [
  ['beauty-advisor', /SALON|BEAUTY|BEAUTE/],
  ['visual-merchandising', /VISUAL/],
  ['retail-store-management', /STORE MANAGEMENT|RETAIL MANAGEMENT/],
  ['retail-operations', /STORE OPERATIONS|RETAIL OPERATIONS|STOCK/],
  ['retail-client-advisor', /^(RETAIL|SALES|STORE|BOUTIQUE|VENTE|SHOP|RETAIL SALES|RETAIL STORES?|STORES?|VENTE RETAIL|RETAIL ASSOCIATES?|SALES ADVISOR|SEASONAL-WORKER|零售|销售)$/],
  ['crm-clienteling', /CRM|CLIENTELING|CLIENT (DEVELOPMENT|ENGAGEMENT)/],
  ['ecommerce-digital', /E-?COMMERCE|DIGITAL|ONLINE|OMNI/],
  ['merchandising-buying', /MERCH|BUYING|ACHAT|PLANNING/],
  ['wholesale-b2b', /WHOLESALE|B2B|TRAVEL RETAIL|EXPORT|COMMERCIAL/],
  ['marketing-communication', /MARKETING|COMMUNICATION|PRESS|MEDIA|\bPR\b|BRAND|CONTENT|EVENT/],
  ['design-creation', /DESIGN|CREATI|STUDIO|STYLE\b|COLLECTION/],
  ['product-development-rd', /PRODUCT DEVELOP|R ?& ?D|RESEARCH|DEVELOPPEMENT|SCIENTIFIC|REGULATORY|LABORAT|INNOVATION|PACKAGING/],
  ['atelier-craft', /ATELIER|WORKSHOP|CRAFT|MAROQUIN|HORLOG|JOAILL|COUTURE|SAVOIR/],
  ['manufacturing-quality', /PRODUCTION|MANUFACTUR|INDUSTRI|QUALIT|USINE|PLANT|MAINTENANCE|HSE|EHS/],
  ['supply-chain-logistics', /SUPPLY|LOGISTI|WAREHOUSE|ENTREPOT|PROCUREMENT|PURCHAS|OPERATIONS|DISTRIBUTION/],
  ['finance', /FINANC|ACCOUNT|COMPTAB|CONTROL|AUDIT|TAX|TREASUR/],
  ['hr-talent', /\bHR\b|\bRH\b|HUMAN|RESSOURCES HUMAINES|TALENT|PEOPLE|LEARNING|FORMATION|TRAINING|EDUCATION|RECRUIT/],
  ['it-data', /\bIT\b|INFORMATI|TECH|DATA|SYSTEM|DIGITAL TECH|SOFTWARE|ENGINEERING/],
  ['legal-compliance', /LEGAL|JURIDI|COMPLIANCE|\bIP\b/],
  ['sustainability', /SUSTAINAB|DURABLE|CSR|RSE|ESG|ENVIRONNEMENT|ENVIRONMENT/],
  ['customer-service', /CUSTOMER (SERVICE|CARE|SUPPORT)|SERVICE CLIENT|CLIENT SERVICE|CALL CENT|CONTACT CENT|AFTER SALES/],
  ['hospitality', /HOSPITALITY|HOTEL|RESTAURANT|F&B|FOOD/],
  ['admin-facilities', /ADMINISTRATI|FACILIT|OFFICE|GENERAL SERVICES|SERVICES GENERAUX|REAL ESTATE|IMMOBILIER/],
  ['strategy-management', /STRATEG|GENERAL MANAGEMENT|DIRECTION GENERALE|EXECUTIVE|CORPORATE|BUSINESS|MANAGEMENT|PROJECT/],
];

/** Un département de salon ou de boutique qui donne sa famille à un titre générique (« Stylist », « General Manager »). */
const SALON_DEPARTMENT_RE = /SALON/;
const SALON_TITLE_RE = /STYLIST|ARTIST|BROW|LASH|WAX|PIERC|COLOR|BARBER|ESTHET|NAIL|SKIN/;
const STORE_DEPARTMENT_RE = /RETAIL MANAGEMENT|STORE MANAGEMENT|^STORES?$|^RETAIL$/;
const STORE_MANAGER_TITLE_RE = /^(GENERAL|ASSISTANT|ASSOCIATE|DEPUTY|SENIOR)? ?MANAGER\b|GENERAL MANAGER|^MANAGER\b/;

/**
 * « Assistant Manager, Network Development », « Team Lead, Client Insights » :
 * le rang est dans la tête, le métier dans la suite — on classe la suite.
 */
const RANK_WORDS_RE = /\b(?:TEMP|TEMPORARY|SENIOR|JUNIOR)?\s?(?:ASSISTANT|ASSOCIATE|DEPUTY|SENIOR|TEAM)?\s?(?:MANAGER|MANAGEUR)\b/;
/** Un reste qui ne nomme que la boutique : on garde le titre entier. */
const SHOP_ONLY_RE = /^(?:(?:SALES|STORE|DEPARTMENT|FLOOR|COUNTER|SHOP|BOUTIQUE|RETAIL|DUTY|SHIFT|TEAM|GENERAL|LEAD|LEADER|I{1,3}|[-–]|\d+|H|F|M|W|D|X|H F|F H|M W D)\s*)+$/;
const RANK_HEAD_RE = /^(TEMP |TEMPORARY |SENIOR |JUNIOR )?(ASSISTANT|ASSOCIATE|DEPUTY|SENIOR|TEAM) (MANAGER|LEAD(ER)?),?\s+(?=\S)/;

function applyRules(t: string): JobFunction | null {
  for (const [fn, re] of FUNCTION_RULES) if (re.test(t)) return fn;
  return null;
}

/** La famille de métier d'une offre, depuis son titre puis son département ; null si rien ne la nomme. */
export function classifyFunction(title: string | null | undefined, department?: string | null): JobFunction | null {
  const t = comparableTitle(title);
  const d = comparableTitle(department);

  // Le département de salon ou de boutique prime sur un titre générique :
  // 4 357 coiffeurs Ulta (« Stylist », dép. « Salon Professionals ») sortaient
  // « Création & design » ; 63 « General Manager » de magasin « Dirigeants ».
  if (d && SALON_DEPARTMENT_RE.test(d) && SALON_TITLE_RE.test(t)) return 'beauty-advisor';
  if (d && STORE_DEPARTMENT_RE.test(d) && STORE_MANAGER_TITLE_RE.test(t)) return 'retail-store-management';

  if (t) {
    // « Assistant Manager, Network Development », « PR Assistant Manager » :
    // le rang est un mot, le métier est le reste — on classe le reste d'abord,
    // sauf quand le reste ne dit que la boutique (« Assistant Store Manager »).
    const tail = t.replace(RANK_HEAD_RE, '').replace(RANK_WORDS_RE, ' ').replace(/\s+/g, ' ').trim();
    if (tail !== t && tail && !SHOP_ONLY_RE.test(tail)) {
      const fromTail = applyRules(tail);
      if (fromTail) return fromTail;
    }
    const fromTitle = applyRules(t);
    if (fromTitle) return fromTitle;
  }
  if (d) {
    for (const [fn, re] of DEPARTMENT_RULES) if (re.test(d)) return fn;
  }
  return null;
}

export function familyOf(fn: JobFunction | null | undefined): JobFamily | null {
  return fn ? FAMILY_OF[fn] ?? null : null;
}

/**
 * Ces trois motifs sont le fruit de mois d'observation réelle (WERKSTUDENT,
 * LEHRSTELLE, AZUBI, NEOLAUREAT, BECARI…). Ils ne classent plus une SÉNIORITÉ —
 * les programmes en sont sortis le 2026-09-08 — mais alimentent `programType`,
 * la dimension à laquelle ils appartenaient depuis le début.
 */
const INTERNSHIP_RE = /\bSTAGE\b|STAGIAIRE|STAGAIRE|INTERN(SHIP)?S?\b|TIROCIN|PRACTICAS|PRAKTIK|ESTAGIO|WERKSTUDENT|PLACEMENT (STUDENT|YEAR)|STUDENT PLACEMENT|\bSTUDENT\b|BECARI/;
const APPRENTICESHIP_RE = /ALTERNAN|APPRENTI|APPRENTICE|APPRENTISSAGE|APPRENDIST|\bLEHRE\b|LEHRSTELLE|LEHRLING|AUSBILDUNG|AUSZUBILDEND|AZUBI|\bELEV\b|WORK[- ]STUDY|DUAL(ES)? (STUD|DEGREE)|CONTRAT (DE )?PRO(FESSIONNALISATION)?\b|LEARNERSHIP/;
const GRADUATE_RE = /GRADUATE|\bV\.?I\.?E\.?\b(?! )|\bVIE\b (?:\d|-|MISSION|PROGRAM|CONTRACT|[A-Z]{2,}\b)|TRAINEE|JEUNE\S* DIPLOM|EARLY CAREER|ROTATIONAL|NEOLAUREAT|MANAGEMENT TRAINING PROGRAM|\bMTP\b/;
/** « CRO Manager » (conversion) n'est pas un Chief Revenue Officer. */
const EXECUTIVE_RE = /\b[SE]?VP\b|VICE[- ]PRESIDENT|\bCHIEF\b|\bC[EFOMTIHR]O\b(?! (MANAGER|SPECIALIST|ANALYST|LEAD|INTERN))|\bCHRO\b|PRESIDENT|MANAGING DIRECTOR|DIRECTEUR\S* GENERAL|DIRECTRICE GENERALE|\bGENERAL MANAGER\b(?! (STORE|BOUTIQUE|ASSISTANT))|\bGM\b|AMMINISTRATORE DELEGATO|GESCHAFTSFUHRER|DIRECTOR GENERAL/;
const DIRECTOR_RE = /DIRECTOR|DIRECTEUR|DIRECTRICE|DIRETTOR|DIREKTOR|\bHEAD OF\b|\bHEAD\b,? |^HEAD\b|RESPONSABLE (DE |DU |DES )?(DEPARTEMENT|DIRECTION|POLE|BUSINESS UNIT|MARCHE|MARKET|REGION)|\bDIRECTION\b (?!ARTISTIQUE)/;
/** Un coordinateur est un contributeur individuel (706 titres prod, audit I-3) : il n'est plus ici. */
const MANAGER_RE = /MANAGER|MANAGEUR|RESPONSABLE|SUPERVIS|TEAM ?LEAD|STORE LEADER|SHOP LEADER|CHEF D'EQUIPE|CHEF DE (BOUTIQUE|MAGASIN|RAYON|SECTEUR|DEPARTEMENT|ZONE|REGION|VENTE|CAISSE|GROUPE|ATELIER|SERVICE)|GERANT|CAPO\b|LEITER|LEITUNG|\bLEAD\b (?:OF|,)|STORE IN CHARGE|PREMIERE? D'ATELIER|ENCARGAD|GERENTE|RESPONSABILE|SOUSCHEF/;
/** Un « manager » qui ne manage pas : titre d'expertise individuelle. */
const IC_MANAGER_RE = /(\bCRO\b|CONVERSION|\bSEO\b|\bSEA\b|PROJECT|PRODUCT|ACCOUNT|BRAND|COMMUNITY|CONTENT|CATEGORY|CAMPAIGN|EVENT|PARTNERSHIP|TRAFFIC|SOCIAL MEDIA|INFLUENCE|CRM|E-?COMMERCE|ECOM|MARKETING|COMMUNICATION|\bPR\b|PRESS|VISUAL MERCHANDISING|MERCHANDISE PLANNING|SUPPLY|DEMAND|PLANNING|QUALITY|QUALITE|MAINTENANCE|FACILIT|OFFICE|PAYROLL|TRAINING|LEARNING|EDUCATION|RECRUIT|SOURCING|LOGISTIC|TRANSPORT|CUSTOMS|COMPLIANCE|RISK|DATA|IT|SYSTEM|APPLICATION|SALESFORCE|SAP|ERP|CRM|PLM|SECURITY|SUSTAINABILITY|CSR|RSE|ESG|BUSINESS DEVELOPMENT|KEY ACCOUNT|WHOLESALE|EXPORT|TRADE|TERRITORY|REGIONAL SALES|CLIENT DEVELOPMENT|CLIENTELING|LOYALTY|TALENT|HR BUSINESS|PEOPLE|CHEF DE PROJET|CHEF DE PRODUIT|CHEF DE MARQUE|RESPONSABLE (DE |DU |DES )?(PROJET|PRODUIT|MARQUE|COMMUNICATION|MARKETING|CRM|E-?COMMERCE|DIGITAL|QUALITE|DEVELOPPEMENT|CLIENTELE|ZONE EXPORT|COMPTE|GRANDS COMPTES|FORMATION|RECRUTEMENT|PAIE|LOGISTIQUE|APPROVISIONNEMENT|PLANNING|SECURITE|MAINTENANCE|ADMINISTRATIF|COMPTABLE|CONTROLE|JURIDIQUE|RSE|DEVELOPPEMENT DURABLE)) (MANAGER|MANAGEUR)?/;
/** « Specialist » / « Expert » ne sont plus seniors : chez Ulta un « Specialist » est un vendeur (audit I-3). */
const SENIOR_RE = /\bSENIOR\b|\bSR\.?\b|CONFIRME|PRINCIPAL|\bLEAD\b|\bIII\b|\bIV\b|STAFF (ENGINEER|DESIGNER)|ARCHITECT|MASTER STYLIST|ELITE STYLIST/;
/**
 * Un « Sales Associate » n'est pas un junior — c'est le poste de vente
 * standard américain (6 160 offres JUNIOR contre « Conseiller de vente » MID,
 * audit I-3). Junior = le mot, ou un assistant d'une fonction corporate.
 */
const JUNIOR_RE = /\bJUNIOR\b|\bJR\.?\b|ENTRY[- ]LEVEL|DEBUTANT|\bTRAINEE\b|AIDE\b|AUXILIAIRE|ASSISTANT\S* (CHEF|CHARGE|MARKETING|COMMUNICATION|RH|COMPTABLE|BUYER|MERCHANDIS|DESIGNER|PRODUCT|PROJECT|BRAND|CRM|E-?COMMERCE|DIGITAL|STYLISTE|COLLECTION|PLANNER|ACHETEU|CONTROLEU|JURISTE|PRESS)|ASSISTANT\S* (DE |D')(PRODUCTION|COLLECTION|COMMUNICATION|MARKETING)/;

/**
 * La séniorité, lue dans le titre puis dans le contrat normalisé. L'ordre des
 * tests fait la règle : « Stage – Assistant Manager » est un stage ; « Senior
 * Store Manager » est un manager ; « Senior Product Manager » est un senior
 * (un product manager ne manage pas d'équipe).
 */
export function classifySeniority(
  title: string | null | undefined,
  department?: string | null,
): Seniority {
  const t = comparableTitle(title);
  // « General Manager » d'un magasin (Ulta : département « Retail Management ») dirige une boutique, pas une entreprise.
  const d = comparableTitle(department);
  if (/GENERAL MANAGER/.test(t) && (/(STORE|RETAIL|BOUTIQUE|SHOP|MAGASIN)/.test(t) || STORE_DEPARTMENT_RE.test(d))) return 'DIRECTOR';
  if (EXECUTIVE_RE.test(t)) return 'EXECUTIVE';
  if (DIRECTOR_RE.test(t)) return 'DIRECTOR';
  if (MANAGER_RE.test(t) && !IC_MANAGER_RE.test(t)) return 'MANAGER';
  if (SENIOR_RE.test(t)) return 'SENIOR';
  if (JUNIOR_RE.test(t)) return 'JUNIOR';
  return 'MID';
}

/**
 * L'annonce parle-t-elle d'IA ? Sigles en capitales strictes — « AI » et
 * « IA » en minuscules sont des mots français — plus les expressions longues,
 * toutes langues. Avant le test, on retire ce qui n'est pas un métier :
 * les phrases de PROCESSUS de recrutement, les clauses d'entreprise, le code
 * de l'Iowa (« Altoona, IA, USA »), la saison « AI 2027 » (Autunno-Inverno).
 */
const AI_ACRONYM_RE = /(?<![''’])\b(?:AI|IA|GENAI|LLMS?|NLP)\b(?![-']?\w)/;
const AI_PHRASE_RE = /artificial intelligence|intelligence artificielle|intelligenza artificiale|inteligencia artificial|k[üu]nstliche intelligenz|machine learning|apprentissage (automatique|machine)|deep learning|generative ai|gen ?ai\b|ia g[ée]n[ée]rative|large language model|computer vision|prompt engineer|chatgpt|openai|neural network|r[ée]seaux? de neurones/i;
/** « data science » compte hors intitulé de diplôme et hors nom d'équipe. */
const DATA_SCIENCE_RE = /data scien/gi;
const DEGREE_CONTEXT_RE = /degree|master|bachelor|b\.?sc|m\.?sc|dipl[oô]m|formation|studies|laurea|[ée]tudiant|background in|analysts?,|scientists,/i;

/**
 * Phrases qui parlent du PROCESSUS de recrutement ou de l'entreprise, pas du
 * poste : « refrain from using AI tools during interviews », « artificial
 * intelligence is not used for hiring decisions », « AI at Toast », « We do
 * not employ machine learning technologies during this phase », « L'IA peut
 * être utilisée à des fins de présélection », « Charte IA : notre pacte ».
 * Mesuré en prod (audit I-3) : 41 % des offres « IA » l'étaient par une de
 * ces phrases recopiées dans chaque annonce d'une société.
 */
const PROCESS_SENTENCE_RE = /interview|entretien|recruit|recrut|hiring (process|decision|team|manager)|selection process|processus de (s[ée]lection|recrutement)|pr[ée]s[ée]lection|screening|candidat|applicant|application(s)? (process|form|will|are|is)|assessment|fraud|scam|privacy|data protection|personal (data|information)|donn[ée]es personnelles|equal (opportunit|employment)|discriminat|accommodation|inteligencia artificial.{0,60}(entrevista|proceso)|refrain|abstenga|prohibit|not permitted|is not used|n'est pas utilis|sans utiliser|ne pas utiliser|do not (employ|use)|train(ing)? (any )?(AI|ML) models|disclos|consent|GDPR|RGPD|Bewerbung|Auswahl|at (toast|infuse)|we (use|leverage|believe|handle|build)|our (mission|pact|values|technology|proprietary)|company values|charte IA|AI charter|notre pacte|founded in|proprietary technology|about (us|the company)|who we are|à propos de/i;

/** Ce qui ressemble à un sigle IA sans en être un : le code de l'Iowa, la saison italienne. */
function stripFalseAcronyms(text: string): string {
  return text
    .replace(/,\s*IA(,|\s+USA|\s+US\b|\s+\d{5})/g, ' ')
    .replace(/\b(?:AI|PE)\s?\/\s?(?:AI|PE)\b|\b(?:SS|AI|PE)\s?\/\s?(?:AI|PE)\s?\d{2,4}|\bAI\s?20\d\d\b|\bAI\s?\d\d\b/g, ' ');
}

export function isAiRelated(title: string | null | undefined, description?: string | null): boolean {
  const body = stripFalseAcronyms((description ?? '').slice(0, 30_000))
    .split(/(?<=[.!?])\s+|\n+|\s[•·▪●-]\s/)
    .filter((sentence) => !PROCESS_SENTENCE_RE.test(sentence))
    .join('\n');
  const text = `${stripFalseAcronyms(title ?? '')}\n${body}`;
  if (AI_PHRASE_RE.test(text) || AI_ACRONYM_RE.test(text)) return true;
  DATA_SCIENCE_RE.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = DATA_SCIENCE_RE.exec(text)) !== null) {
    const window = text.slice(Math.max(0, match.index - 45), match.index + match[0].length + 45);
    if (!DEGREE_CONTEXT_RE.test(window)) return true;
  }
  return false;
}

/** Les mots d'IA dans un TITRE : la garde par société ne conserve que ceux-là. */
export const AI_TITLE_RE = /\b(?:AI|IA|ML|GENAI|LLM|NLP)\b|MACHINE LEARNING|ARTIFICIAL INTELLIGENCE|INTELLIGENCE ARTIFICIELLE|DATA SCIEN|DEEP LEARNING|COMPUTER VISION|PROMPT/;

export type JobClassification = {
  jobFunction: JobFunction | null;
  seniority: Seniority;
  isRetail: boolean | null;
  isAiRelated: boolean;
  skills: string[];
  taxonomyVersion: number;
  /** Le dispositif nommé par l'intitulé — dimension distincte de la séniorité. */
  programType: ProgramType | null;
};

/**
 * Le DISPOSITIF que nomme un intitulé, ou `null`.
 *
 * Réutilise les motifs multilingues éprouvés ci-dessus. Le plus spécifique
 * gagne : « Graduate Program » et « V.I.E » avant l'alternance, elle-même avant
 * le stage — « Management Trainee Program » est un parcours de jeune diplômé,
 * pas un stage.
 */
export function classifyProgramType(title: string | null | undefined): ProgramType | null {
  const t = comparableTitle(title);
  if (GRADUATE_RE.test(t)) return /\bV\.?I\.?E\.?\b/.test(t) ? 'VIE' : 'GRADUATE_PROGRAM';
  if (APPRENTICESHIP_RE.test(t)) return 'APPRENTICESHIP';
  if (INTERNSHIP_RE.test(t)) return 'INTERNSHIP';
  return null;
}

/** Tout ce que la taxonomie écrit sur une offre, en une passe. */
export function classifyJob(input: {
  title: string | null | undefined;
  department?: string | null;
  description?: string | null;
}): JobClassification {
  const jobFunction = classifyFunction(input.title, input.department);
  const family = familyOf(jobFunction);
  return {
    jobFunction,
    seniority: classifySeniority(input.title, input.department),
    programType: classifyProgramType(input.title),
    isRetail: family === null ? null : family === 'retail',
    isAiRelated: isAiRelated(input.title, input.description),
    skills: extractSkills(`${input.title ?? ''}\n${input.description ?? ''}`),
    taxonomyVersion: TAXONOMY_VERSION,
  };
}
