import { PrismaClient } from '@prisma/client';
const p = new PrismaClient();
const sample = await p.$queryRaw<{ title: string; department: string | null; jobFunction: string | null; seniority: string | null; isAiRelated: boolean; skills: string[] }[]>`SELECT title, department, "jobFunction", seniority, "isAiRelated", skills FROM "Job" WHERE "isActive" ORDER BY md5(id) LIMIT 220`;
console.log('=== SAMPLE 220 (title | dept | function | seniority | ai | skills≤4)');
for (const r of sample) console.log(`${r.title.slice(0, 60).padEnd(60)} | ${(r.department ?? '').slice(0, 18).padEnd(18)} | ${(r.jobFunction ?? '—').padEnd(26)} | ${(r.seniority ?? '—').padEnd(14)} | ${r.isAiRelated ? 'AI' : '  '} | ${r.skills.slice(0, 4).join(', ')}`);
const ai = await p.$queryRaw<{ title: string; n: bigint }[]>`SELECT title, count(*)::bigint n FROM "Job" WHERE "isActive" AND "isAiRelated" GROUP BY 1 ORDER BY 2 DESC LIMIT 40`;
console.log('=== TOP AI-FLAGGED TITLES'); for (const r of ai) console.log(Number(r.n), r.title.slice(0, 90));
const dist = await p.$queryRaw<{ f: string; n: bigint }[]>`SELECT COALESCE("jobFunction",'—') f, count(*)::bigint n FROM "Job" WHERE "isActive" GROUP BY 1 ORDER BY 2 DESC`;
console.log('=== FUNCTION DISTRIBUTION'); for (const r of dist) console.log(String(Number(r.n)).padStart(6), r.f);
const sen = await p.$queryRaw<{ s: string; n: bigint }[]>`SELECT COALESCE(seniority,'—') s, count(*)::bigint n FROM "Job" WHERE "isActive" GROUP BY 1 ORDER BY 2 DESC`;
console.log('=== SENIORITY'); for (const r of sen) console.log(String(Number(r.n)).padStart(6), r.s);
const lang = await p.$queryRaw<{ s: string; n: bigint }[]>`SELECT s, count(*)::bigint n FROM "Job", unnest(skills) s WHERE "isActive" GROUP BY 1 ORDER BY 2 DESC LIMIT 40`;
console.log('=== TOP SKILLS'); for (const r of lang) console.log(String(Number(r.n)).padStart(6), r.s);
const un = await p.$queryRaw<{ t: string; n: bigint }[]>`SELECT regexp_replace(upper(title), '\s*\(.*?\)|\s*[-–|].*$', '', 'g') t, count(*)::bigint n FROM "Job" WHERE "isActive" AND "jobFunction" IS NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 60`;
console.log('=== TOP UNCLASSIFIED'); for (const r of un) console.log(String(Number(r.n)).padStart(5), r.t.slice(0, 80));
await p.$disconnect();
