import { chromium } from 'playwright';
const out = '/private/tmp/claude-501/-Users-lmelane-Downloads-catwalks-job-aggregator/cb987be9-6318-41c2-be50-828162123854/scratchpad';
const b = await chromium.launch(); const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:3121/', { waitUntil: 'networkidle' });
await page.screenshot({ path: `${out}/verify-home-hero.png`, clip: { x: 0, y: 200, width: 1440, height: 420 } });
console.log('hero h1:', JSON.stringify(await page.textContent('h1')));
await page.goto('http://localhost:3121/intelligence', { waitUntil: 'networkidle' });
await page.screenshot({ path: `${out}/verify-intel-top.png`, clip: { x: 0, y: 0, width: 1440, height: 900 } });
console.log('kpi values:', JSON.stringify(await page.$$eval('.kpi__value', (els) => els.slice(0, 4).map((e) => e.textContent))));
await b.close();
