import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { afterEach, describe, expect, it, vi } from 'vitest';
import * as http from '../../lib/http.js';
import { fetchIcimsJobs, parseIcimsListing } from './icims.js';

/*
 * Réponses réelles d'urbn-hub, corps archivés en production (le SHA-256 de chaque fichier est la clé du RawBlob) :
 *  - la page de liste du RUN du 28/09/2026 (lot 5144c281, séquence 7, 18:38:59) qui porte la carte de l'offre 31752 ;
 *  - la fiche de 31752 dans le même lot à 18:42:01, 02 et 03 (séquences 417, 418, 421) : trois fois HTTP 502, le même
 *    corps CloudFront « The origin closed the connection », daté de la même seconde (18:42:00) — l'erreur mise en
 *    cache par le CDN, que les relances immédiates du transport relisent ;
 *  - la même fiche quinze minutes plus tôt dans le même RUN (lot 912030a2, séquence 412, 18:27:45) : HTTP 200.
 * Le 28/09, sans relecture, l'offre est restée retenue ICIMS_DETAIL_FETCH_FAILED (« 1 à instruire ») et urbn-hub est
 * passé en DEGRADED ; la fiche répondait 200 le lendemain (`scripts/ops/mesures/fiches-en-echec.mts --kind=icims`).
 */
const fixture = (name: string) => gunzipSync(readFileSync(new URL(`./__fixtures__/${name}`, import.meta.url))).toString('utf8');
const sha256 = (text: string) => createHash('sha256').update(text).digest('hex');
const listing = fixture('icims-urbn-liste-31752-20260928.html.gz');
const gateway = fixture('icims-urbn-31752-502-cloudfront-20260928.html.gz');
const detail = fixture('icims-urbn-31752-fiche-20260928.html.gz');
const TARGET = '31752';
/** La configuration du registre, telle quelle ; seul le délai de relecture est raccourci pour le test. */
const config = { origin: 'https://hub-urbn.icims.com', employerFromJobPosting: true, detailRetryDelayMs: 0,
  detailOrigins: ['https://homeoffice-eu-urbn.icims.com', 'https://homeoffice-na-urbn.icims.com', 'https://menusandvenues-na-urbn.icims.com',
    'https://stores-eu-urbn.icims.com', 'https://stores-na-urbn.icims.com', 'https://supplychain-eu-urbn.icims.com', 'https://supplychain-na-urbn.icims.com'] };
const targetUrl = parseIcimsListing(listing).find(job => job.externalId === TARGET)!.url;

/**
 * La liste sert la page réelle, puis la répète (fin de lecture, comme un portail iCIMS). Chaque fiche répond, lecture
 * après lecture, ce que `plan(url)` prévoit : `502` lève comme le transport après ses trois tentatives, `fiche` rend
 * la fiche archivée de 31752, `vide` une page sans JobPosting (les autres offres, dont les fiches ne sont pas ici).
 */
function serve(plan: (url: string) => Array<'502' | 'fiche' | 'vide'>) {
  const calls = new Map<string, number>();
  vi.spyOn(http, 'fetchText').mockImplementation(async (url: string) => {
    if (url.includes('/jobs/search')) return listing;
    const n = calls.get(url) ?? 0; calls.set(url, n + 1);
    const steps = plan(url);
    const answer = steps[Math.min(n, steps.length - 1)];
    if (answer === '502') throw new http.HttpStatusError(502, url);
    return answer === 'fiche' ? detail : '<html><body></body></html>';
  });
  return calls;
}
const target = (jobs: Array<{ externalId: string }>) => jobs.find(job => job.externalId === TARGET) as
  { publicationHold?: string; description?: string; company?: string } | undefined;
afterEach(() => vi.restoreAllMocks());

describe('iCIMS : une fiche en échec est relue une fois, plus tard (urbn-hub, RUN du 28/09/2026)', () => {
  it('prémisse : réponses archivées ; la fiche lue lève la retenue ; en échec, l\'offre reste à instruire', async () => {
    expect(sha256(listing)).toBe('aef5420750ddbc6c38574fc48f8c8d52381a8e0c9f5524b151588a7d5c0df3ee');
    expect(sha256(gateway)).toBe('a3ced5760919895437471efbae4bc7bbee0b7c2b0a606439cdc5a60a8e6cfb41');
    expect(sha256(detail)).toBe('57ba70f1f603ea414788f692780850a1bbfa464fdfddf56da129f14686928efb');
    expect(gateway).toContain('The origin closed the connection');
    expect(gateway).toContain('Generated by cloudfront');
    expect(new URL(targetUrl).origin).toBe('https://stores-na-urbn.icims.com');
    const cards = parseIcimsListing(listing);
    expect(cards.length).toBeGreaterThan(20);
    // La fiche du même RUN, lue seule : l'offre sort sans retenue, avec sa description.
    serve(url => url === targetUrl ? ['fiche'] : ['vide']);
    const ok = target((await fetchIcimsJobs(config)).jobs);
    expect(ok?.publicationHold).toBeUndefined();
    expect(ok?.description?.length).toBeGreaterThan(500);
    // Ce que le 28/09 a produit : la fiche en 502, l'offre retenue ICIMS_DETAIL_FETCH_FAILED.
    vi.restoreAllMocks();
    serve(url => url === targetUrl ? ['502'] : ['vide']);
    const lost = target((await fetchIcimsJobs(config)).jobs);
    expect(lost?.publicationHold).toBe('ICIMS_DETAIL_FETCH_FAILED');
    expect(lost?.description).not.toBe(ok?.description);
  });

  it('le 502 du 28/09 puis la fiche : relue une fois, l\'offre sort sans retenue', async () => {
    const calls = serve(url => url === targetUrl ? ['502', 'fiche'] : ['vide']);
    const job = target((await fetchIcimsJobs(config)).jobs);
    expect(calls.get(targetUrl)).toBe(2);
    expect(job?.publicationHold).toBeUndefined();
    expect(job?.description?.length).toBeGreaterThan(500);
  });

  it('une fiche toujours en échec : lue deux fois, jamais plus, retenue comme avant', async () => {
    const calls = serve(url => url === targetUrl ? ['502'] : ['vide']);
    const job = target((await fetchIcimsJobs(config)).jobs);
    expect(calls.get(targetUrl)).toBe(2);
    expect(job?.publicationHold).toBe('ICIMS_DETAIL_FETCH_FAILED');
  });

  it('toutes les fiches en échec : panne du portail, aucune relecture', async () => {
    const calls = serve(() => ['502']);
    const result = await fetchIcimsJobs(config);
    expect([...calls.values()].every(n => n === 1)).toBe(true);
    expect(result.jobs.every(job => job.publicationHold === 'ICIMS_DETAIL_FETCH_FAILED')).toBe(true);
  });

  it('au-delà de la borne (plus de 5 fiches et de 5 %) : aucune relecture', async () => {
    const failing = new Set(parseIcimsListing(listing).slice(0, 6).map(job => job.url));
    const calls = serve(url => failing.has(url) ? ['502', 'fiche'] : ['vide']);
    await fetchIcimsJobs(config);
    expect([...failing].map(url => calls.get(url))).toEqual([1, 1, 1, 1, 1, 1]);
  });
});
