import csv,json,pathlib,re,unicodedata
root=pathlib.Path(__file__).parent;p=root/'evidence';rows=[]
cs=json.loads((p/'companies.json').read_text());ss=json.loads((p/'sources.json').read_text());roster=list(csv.DictReader(open('apps/aggregator/data/maisons.csv')))
def norm(s):return re.sub('[^a-z0-9]','',unicodedata.normalize('NFKD',s.lower()).encode('ascii','ignore').decode())
def add(name,kind,sector,country,domain,career,ats,proof,note,group='',aliases='',priority='P1',state='SOURCE_A_VALIDER'):
 matches=[c for c in cs if norm(c['name'])==norm(name) or (domain and c['domain']==domain)]
 rows.append(dict(priorite=priority,identite_canonique_proposee=name,type_propose=kind,univers=sector,pays_identite_ou_perimetre=country,aliases_observes=aliases,groupe_parent_prouve=group or 'NON_ETABLI',domaine_officiel=domain or 'NON_VERIFIE',portail_carriere=career or 'NON_TROUVE',ATS=ats or 'NON_IDENTIFIE',preuve=proof,verifie_le='2026-09-08',confiance_identite='A_CONFIRMER' if not domain else 'DOMAINE_ET_IDENTITE_DOCUMENTES',confiance_source='NON_CALIBREE; portail cité ne vaut pas validation de collecte',validation_technique='NON_EXECUTEE_PENDANT_AUDIT',statut=state,offres_sous_identites_ou_domaine_base=sum(c['active']for c in matches),identites_base=' | '.join(c['name']for c in matches),present_dans_roster_728=any(norm(name)==norm(r.get('name','')) for r in roster),notes=note,avant_activation='Identité + propriétaire du portail; alias et groupe; tenant unique; robots daté; parse réel sans écriture; pagination complète; géographie et marque par offre; validation revue. Aucune activation pendant cet audit.'))
add('Jacquemus','MAISON','FASHION','FR','jacquemus.com','https://jobs.eu.lever.co/jacquemus','Lever EU','https://jobs.eu.lever.co/jacquemus','37 annonces nommées et une candidature spontanée visibles; absence d’identité en base; ne pas compter la candidature spontanée comme poste.',aliases='JACQUEMUS')
add('Saint James','MAISON','FASHION','FR','saint-james.com','https://rejoindrenotreequipage.saint-james.com/','WeRecruit','https://fr.saint-james.com/pages/08-notre-equipe','Portail relié officiellement; 5 offres affichées; signature WeRecruit observée.',aliases='SAINT JAMES | Tricots Saint James')
add('Armor-lux','MAISON','FASHION','FR','armorlux.com','https://careers.werecruit.io/fr/armor-lux','WeRecruit','https://www.armorlux.com/','Lien Recrutement officiel vers WeRecruit; volume complet non établi.',aliases="Armor Lux | Bonneterie d’Armor")
add('Aesop','MAISON','BEAUTY','FR / international','aesop.fr','https://www.aesop.fr/careers.html','Avature + Workday','https://www.aesop.fr/careers.html',"Deux parcours officiels : boutiques via careers.loreal.com et bureaux via aesop.wd3.myworkdayjobs.com. Couverture éventuelle sous L’Oréal à isoler avant ajout.",group="L’Oréal",aliases='AESOP')
add('Rouje','MAISON','FASHION','FR','rouje.com','https://fr.fashionjobs.com/entreprise/rouje,105406,67371.html','FashionJobs','https://www.rouje.com/pages/marque-employeur','Company existe mais zéro offre active; lien officiel confirmé; vérifier couverture FashionJobs existante avant créer un nouveau flux.')
add('Groupe NOVI','GROUP','BEAUTY','FR','groupe-novi.com','https://groupe-novi.com/nous-rejoindre/','Portail web; ATS non établi','https://groupe-novi.com/nous-rejoindre/','Offres datées visibles. Beauty Success est déjà couvert (109 offres); ne pas le recréer. Établir les relations vers les autres enseignes.',aliases='NOVI')
add("L’Atelier du Sourcil",'RETAILER','BEAUTY','FR','','https://groupe-novi.com/nous-rejoindre/','NON_IDENTIFIE','https://catwalks.io/maisons/l-atelier-du-sourcil','Piste de portail groupe; lien de propriété à documenter explicitement avant rattachement. 5 offres sur Catwalks recrutement ne prouvent pas 5 offres dans cet agrégateur.',aliases="L'Atelier du sourcil",state='IDENTITE_ET_SOURCE_A_CONFIRMER')
add('Messika','MAISON','JEWELRY_WATCHES','FR','messika.com','https://www.linkedin.com/company/messika','LinkedIn / JobTeaser; flux non validé','https://fr.linkedin.com/posts/messika_hiring-messika-activity-7433088582057185280-u-8D','Communication employeur officielle. REJETER le portail trouvé intitulé Messika Demo sur softgarden : pas de preuve de portail de production.',aliases='MESSIKA PARIS')
for name,domain,proof,alias in [('Bon Parfumeur','bonparfumeur.com','https://www.bonparfumeur.com/fr','Bon Parfumeur Paris'),('Essential Parfums','essentialparfums.com','https://us.essentialparfums.com/','ESSENTIAL PARFUMS'),('Ex Nihilo','ex-nihilo-paris.com','https://www.ex-nihilo-paris.com/fr/la-maison','EX NIHILO PARIS'),('Maison Crivelli','maisoncrivelli.com','https://maisoncrivelli.com/fr-fr/collections','Crivelli')]:
 add(name,'MAISON','BEAUTY','FR',domain,'','',proof,'Identité commerciale vérifiée; aucun portail carrière officiel exploitable confirmé. Zéro offre ne peut pas être interprété comme absence de recrutement.',aliases=alias,state='PORTAIL_NON_ETABLI')
add('Lise Charmel','MAISON','FASHION','FR','lisecharmel.com','https://www.lisecharmel.com/lc_fr_fr/carrieres','Candidature par contact; pas de listing','https://www.lisecharmel.com/lc_fr_fr/carrieres','Page officielle de candidature spontanée, sans catalogue de postes. Ne pas inventer une offre ni une source ATS.',state='PAS_DE_FLUX_OFFRES_ETABLI')
add('Inditex','GROUP','FASHION','ES / FR / international','inditex.com','https://www.inditexpeople.com/fr/fr','Portail Inditex People; moteur à qualifier','https://www.inditexpeople.com/fr/fr','10 offres en base via FashionJobs; aucune source Inditex dédiée. Prévoir un seul tenant groupe et des relations vers les marques.',aliases='INDITEX')
for name,alias in [('Zara','ZARA'),('Pull&Bear','Pull & Bear'),('Massimo Dutti','MASSIMO DUTTI'),('Bershka','BERSHKA'),('Stradivarius','STRADIVARIUS'),('Oysho','OYSHO'),('Zara Home','ZARA HOME'),('Lefties','LEFTIES'),('Tempe','TEMPE')]:
 add(name,'SUPPLIER' if name=='Tempe' else 'RETAILER','FASHION','ES / international','zara.com' if name=='Zara' else '', 'https://www.inditexpeople.com/fr/fr','Portail groupe à qualifier','https://www.inditexpeople.com/fr/fr','Marque/acteur nommé par le portail officiel; domaine propre à vérifier si non renseigné. Ne pas créer un connecteur pour chaque enseigne du même tenant.',group='Inditex',aliases=alias)
for name,note in [('SMCP','23 offres explicitement SMCP enregistrées sous Sandro.'),('Maje','148 offres explicitement Maje enregistrées sous Sandro, dont 32 FR; Company Maje affiche zéro.'),('Claudie Pierlot','69 offres explicitement Claudie Pierlot sous Sandro, dont 39 FR.'),('Fursac','35 offres explicitement Fursac sous Sandro, dont 30 FR.')]:
 add(name,'GROUP' if name=='SMCP' else 'MAISON','FASHION','FR / international','smcp.com' if name=='SMCP' else '', 'https://www.smcp.com/en/talents/job-offers/?start=0','SmartRecruiters; Greenhouse pour Amérique du Nord','https://www.smcp.com/en/talents/job-offers/?start=0',note+' Réparer le mapping Brands du tenant déjà présent; ne pas dupliquer la collecte.',group='' if name=='SMCP' else 'SMCP',priority='P0',state='RATTACHEMENT_ERRONE_DEMONTRE')
add('Patou','MAISON','FASHION','FR','patou.com','https://www.patou.com/fr/pages/hr-enquiries','LVMH Careers','https://www.patou.com/fr/pages/hr-enquiries','La Maison renvoie au portail LVMH déjà collecté. Vérifier présence réelle et attribution; absence Company ne prouve pas défaut de collecte.',group='LVMH',aliases='Jean Patou')
add('Fusalp','MAISON','FASHION','FR / international','fusalp.com','https://fusalp.welcomekit.co/','Welcome to the Jungle / WelcomeKit','https://fusalp.welcomekit.co/','21 offres sous Fusalp + CREATIONS FUSALP; 18 visibles sur le portail consulté. Source directe RETIRED mais couverture via boards; réconcilier IDs avant conclure au manque.',aliases='CREATIONS FUSALP',state='COUVERTURE_A_RECONCILIER')
add('Akris','MAISON','FASHION','CH / international','akris.com','https://www.linkedin.com/company/akris_2/jobs','LinkedIn officiel','https://us.akris.com/pages/careers',"Lien officiel vers LinkedIn. Ne pas confondre avec AKRIS GROUP WeRecruit (homonyme à vérifier).",priority='P2')
add('Paul Smith','MAISON','FASHION','GB / international','paulsmith.com','https://www.paulsmith.com/uk/info/careers','NON_VERIFIE','https://www.linkedin.com/company/paul-smith','Lien carrière déclaré sur le profil employeur; page répond 403 à cette consultation. Jobtrain retrouvé historiquement seulement, à revalider.',priority='P2',state='ACCES_ET_ATS_A_VERIFIER')
add('Dries Van Noten','MAISON','FASHION','BE / FR','driesvannoten.com','https://www.driesvannoten.com/en-eu/pages/career-open-positions','Page HTML officielle','https://www.driesvannoten.com/en-eu/pages/career-open-positions','Deux annonces visibles, dont Sales Associate Paris; groupe parent à vérifier avant enregistrement.',priority='P1')
add('Thom Browne','MAISON','FASHION','US / international','thombrowne.com','https://www.linkedin.com/company/thom-browne-inc-/jobs/','LinkedIn officiel','https://www.thombrowne.com/en-mo/pages/contact','Lien carrière confirmé dans le HTML officiel; groupe parent et extraction à valider.',priority='P2')
add('Grand Seiko','MAISON','JEWELRY_WATCHES','JP / FR','grand-seiko.com','','','https://www.grand-seiko.com/fr-fr/support','Entité Grand Seiko Europe identifiée; portail carrière non confirmé. Priorité horlogerie internationale.',priority='P2',state='PORTAIL_NON_ETABLI')
add('Harrods','RETAILER','LUXURY','GB','harrods.com','https://www.harrodscareers.com/jobs/','Moteur à qualifier','https://www.harrods.com/en-gb/c/faqs/other','Portail officiel avec annonces; aucune identité ou source trouvée dans le catalogue.',priority='P1')
add('El Corte Inglés','RETAILER','RETAIL','ES / PT','elcorteingles.es','https://empleo.elcorteingles.es/','Moteur à qualifier','https://www.elcorteingles.es/informacioncorporativa/es/contacto/','Portail officiel du groupe; filtrer le périmètre mode/beauté/luxe des autres activités.',aliases='El Corte Ingles',priority='P2')
add('Takashimaya','RETAILER','RETAIL','JP','takashimaya.co.jp','https://www.takashimaya.co.jp/corp/recruit/','Portail HTML et sous-portails','https://www.takashimaya.co.jp/corp/recruit/career/job/','Postes professionnels visibles; séparer programmes diplômés fermés et recrutements en cours, plus les filiales.',aliases='高島屋',priority='P2')
add('Isetan Mitsukoshi','GROUP','RETAIL','JP','imhds.co.jp','https://www.imhds.co.jp/recruit/index.html','Portail groupe et sous-portails','https://www.imhds.co.jp/recruit/index.html','Présence institutionnelle vérifiée. Campagne nouveaux diplômés clôturée; ne pas transformer toute page recrutement en poste ouvert.',aliases='三越伊勢丹 | Mitsukoshi Isetan',priority='P2')
with (root/'tableaux'/'maisons-sources-a-instruire.csv').open('w',newline='',encoding='utf-8-sig') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
print('Fiches de qualification',len(rows))
